### ISSUE TITLE
Restructuring PowEmailConfirmation IAW Elixir de-facto.

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#11]
I'm looking over the extension `PowEmailConfirmation` to find fn `confirm!` which is required in dev seed and tests.

And I found that this extension has a lot different style than Elixir de-facto standards two mainly;

1) `PowEmailConfirmation.Plug` - Plug only and should implement two functions `init/1` and `call/2`. I believe this module is sufficient to be renamed `PowEmailConfirmation` to avoid conflict and excessive encapsulation. (This is applied to the other modules as well.)
2) `Pow.UUID` - I cannot find any reason to replace the `Ecto.UUID` or `elixir_uuid`. We don't need to reinvent the wheel.

**Comment by jung-hunsoo** [comment]
I'm afraid that the overall `Pow` structure is a bit over complex; too much encapsulation and modularization.

This was familiar with Java-style like Module-for-module (yes I like KISS, Keep-It-Simple-Stupid), but actually `User/session management` isn't that much of a hard thing.

There's one reason why `module-for-module` is not a good fit in Elixir; OO concepts like `extend`, `implement`, `interface`, or `abstract` might be less useful.

How about re-style `Pow` more lightweight, simple and intuitive structure? It will make code more manageable, less error-prone, welcome developers. I believe most of the possible `Pow` users just want to add door to their house, not a barricade.

**Comment by danschultzer** [comment]
I hear you. The encapsulation is so both Ecto and Phoenix can be optional dependencies instead of hard requirements. I'll have to think how Pow can be made easier to work with in this regard. Any thoughts or suggestions are most welcome!

1. Yeah, I should rename these files so there won't be this confusion.  All the `plug.ex` modules in Pow only contains methods for transforming plug connections rather than being a plug.

2. The reason I extracted the UUID generation from Ecto is that Ecto will be an optional dependency in the near future, else I would just have used it directly from Ecto. Same goes for the PBKDF2 generator. I did think about using `elixir_uuid`, but I aim to keep very few dependencies requirements for Pow.

Thanks for your input, it'll help me shape Pow in the right direction.

**Comment by danschultzer** [comment]
Also, for the `confirm!` method, this is the one you'll be looking for: https://github.com/danschultzer/pow/blob/master/lib/extensions/email_confirmation/ecto/context.ex#L17-L25

I've updated the extension readme accordingly: https://github.com/danschultzer/pow/tree/master/lib/extensions/email_confirmation#test-and-seed

**Comment by jung-hunsoo** [comment]
@danschultzer Thanks for the instant response.

I think you have a bigger sketch not just to provide a `user management service`. You're right that the authentication could be performed w/o DB as well. A persistence function that DB is carrying out will be replaced with other methods someday. Style like lambda-db, or refreshing token on every handshake, or others that aren't figured yet.

I was about to revert `Pow` to `Coh...` back, but now I'm implementing `Pow` more. This is more interesting than I expected some hours ago.

**Comment by danschultzer** [comment]
Exactly! I try to strike the balance between having Pow being both easy to use and understand, and super versatile.

That balance will take some time to find, but I hope that in the end Pow will work for any project size, from the small project where, as you said, just the door for the house is needed, to large complex umbrella apps that requires heavy customization and authorization flow control.

Actually, I created Pow because Coherence, et al, didn't work for a complex production umbrella app I was working on. I kept running my head against the wall, so out of necessity I built Pow 😄

**Comment by danschultzer** [comment]
There's another way of solving that pipe issue:

```elixir
%User{}
|> User.changeset(user_params)
|> PowEmailConfirmation.Ecto.Schema.confirm_email_changeset()
|> Pow.Ecto.Context.do_insert(otp_app: :my_app)
```

Then you'll also only carry out a single db operation too.

Most places it has been more natural to pipe config in as first argument in actions like `confirm_email`.

**Comment by jung-hunsoo** [comment]
Thanks. I think it's feasible to cover most use cases than other as long as modules and structures are defined and manged well.

Coherence is also great and it'll do the right job in its place.

**Comment by danschultzer** [comment]
I've experimented with renaming `Pow.Plug` to `Pow.Plug.Helpers` (likewise for extensions), and I think this may make more sense for the structure: https://github.com/danschultzer/pow/pull/14

So now all the plug helper methods be in `lib/plug/helpers.ex`:

```elixir
Pow.Plug.Helpers.current_user(conn, config)
Pow.Plug.Helpers.assign_current_user(conn, user, config)
Pow.Plug.Helpers.authenticate_user(conn, params)
Pow.Plug.Helpers.create_user(conn, params)
```

I'm not sure that the `Helpers` name is good though, so I'll have to think about this before I'll merge in the PR. Once merged, I'll push a new release 🚀

**Comment by danschultzer** [comment]
Also, the current Plug is based on [Guardian](https://github.com/ueberauth/guardian/blob/master/lib/guardian/plug.ex).

**Comment by jung-hunsoo** [comment]
Neither do I. `Helpers` doesn't seem to be welcomed.

It's worth take a look that the elixir core [lib](https://github.com/elixir-lang/elixir/tree/master/lib/elixir/lib) is keeping their module fat, rather than segregated. Not a bad idea, but I think there's a better way.

Personally I'm favorable for `Pow.Operations` structure; it separates external behaviours from core modules. Like an interface in OO, this is safer and yields more flexible. (which I've been thinking about.) But adopting interface and extend concepts to Fn isn't a good deal either. Elixir already allows overriding. Multiple inheritance can be mimicked, but as you can expect, this is the start of pain and hell of maintenance like dependency problems. It will definitely bar the developers.

Actually this is not just a mere Pow issue anymore, but another worth take a look.

**Comment by danschultzer** [comment]
Yeah. Seems like the concept we're getting at will require a more involved restructuring of Pow, and not just the `Pow.Plug` modules themselves. So for now I'll let it stay in its current state until I've found a more suitable setup.

**Comment by jung-hunsoo** [comment]
What criteria did you have in mind placing functions between `Plug` and `Operations`? It seems that the `Operations` is a high-level general interface while `Plug` is aware of phoenix-specific. These are a bit confusing on their roles.

**Comment by danschultzer** [comment]
`Plug` will transform a connection, and `Operations` will work (like you wrote) as a high-level API layer to the Ecto context modules (or whatever is used to store the data). You can see how I use this to unit test Plug without Ecto: https://github.com/danschultzer/pow/blob/master/test/support/context_mock.ex

A connection transformation will look like this:

```
request
  |
  V
Plug (or Phoenix with Plug)
  |
  V
Operations
  |
  V
Ecto (or any ORM/data wrapper)
```

The `Operations` methods could just have been built into the `Plug` module, but I find it more ergonomic to have this distinct middle layer between the plug and context module(s).

On a side note, Phoenix is aware of Plug, but Plug isn't aware of Phoenix. The Phoenix modules wraps around the Plug modules, and Plug is where all the connection transformations happen. My ideal version of Pow is that developers could go ahead and use e.g. [Raxx](https://github.com/CrowdHailer/raxx) instead of Phoenix.

Does this make it more clear on the thoughts behind `Operations`?

**Comment by jung-hunsoo** [comment]
Well, I see. That's clear enough.

**Comment by jung-hunsoo** [comment]
Another thing to check is here.

I thought that `Plug` and Operations` are separated in their job like MVC. But in the codes, `Plug` is working like another wrapper module of `Operations`.

For example, `Pow.Plug.create_user/2` is not only `create a new session` but also calls `Pow.Operations.create/2`.

When I was looking for a fn doing `reload current_user from DB`, the `Pow.Plug.update_user/2` fn seemed to be ok. But in the codes it `really update user DB record` not just `reload :current_user`. Instead `Pow.Plug.Session.do_fetch/1` looks like `refresh current_user from DB`, not sure.

What can I use fn for this situation, and I want to know they are good to locate in `Plug`.

**Comment by danschultzer** [comment]
It's something I've been thinking about ever since I started building Pow. And I think that reload of the current user should only happen whenever the actual user is updated. This would be achieved with an event that Ecto sends, and the credentials store can pick up.

The actual call to update the cached user struct exists in [`Pow.Store.CredentialsCache.put/4`](https://github.com/danschultzer/pow/blob/master/lib/pow/store/credentials_cache.ex#L30-L42). It can be seen in [`Pow.Plug.Session.create/3`](https://github.com/danschultzer/pow/blob/f8798ac1334389cc1ecce6d20d8d7ea97d1c155f/lib/pow/plug/session.ex#L66-L94) how it's used. Of course, both these methods are super low level, and it might be good to have some high level method to update the cached user.

Could you show me an example of when you would need to update the cached user?

**Comment by jung-hunsoo** [comment]
There's a User table and a Userinfo table, which is `has_one` relation. The reason I made a chile table `Userinfo` is 1) it has less frequently loaded fields (they don't need to be always loaded in `conn`), 2) it's separated from external authentication library, `Pow`, in case of update, 3) it's convenient to separate editing sensitive attributes, 4) easy to change schema.

And there's a page where user can update their record. After updating `user` data, a session is expected to refresh assigned `current_user` as well.

It was actually occurred when migrating from `Coh..`. Old source was `apply(Coherence.Config.auth_module, Coherence.Config.update_login, [conn, user, [id_key: Coherence.Config.schema_key]])`. [doc](https://github.com/smpallen99/coherence#updating-the-user-model)

In the current controller, it just utilizes `Pow.Plug.update_user(conn, user_params)` and no manual refresh is called. It seems that the fn is refreshing `current_user` automatically.

**Comment by danschultzer** [comment]
Yeah, `Pow.Plug.update_user/2` will automatically refresh the session. This also means that the session id rotates for security. I think a method to just update the cached user struct would be useful, and will work well when I’ll add event messages for Ecto actions. But you don’t have to think about updating the cached user as long as you’re using `update_user/2`.

**Comment by danschultzer** [comment]
Also if the UserInfo struct won’t be required to have been preloaded in the cached user struct, you won’t have to refresh the cached User struct. You can just preload when necessary in a plug action.

**Comment by abartier** [comment]
I join the debate, reading this issue I feel less alone about few points! 

1) There is a complexity in pow that @jung-hunsoo described well. It's not so bad but it requires a lot of time and reading (and navigation in folders) to understand where the info/conn is going and how it's gonna be transformed. 
2) The pieces of information in current_user  should be customizable for the reasons mentioned here and for security purpose (I tend to expose the less info I can even if they are encrypted)

As far as I understand the objective of pow is to give two paths to the user, one very simple (nearly a one-click installation) and a path more complex where you can customize what is happening. 
I believe that we will all try the second path sooner or later. I mean that we came here for the reason we don't want to reinvent the wheel each time we're building an app. And maintaining the security part is critical (that's why I prefer helping an existing project than building my own solution or leave a custom one in each app I wrote). 

With that in mind, I think that pow let us use a bunch of functions/plugs to achieve what we want. I think that pow could be simplified by reinforcing the idea of an interface exposing those plugs. I see pow as a gatekeeper and I just need to ask or give him information to get a simple response or a way key to enter the private area. 

Gatekeeper.authenticate_user(conn, user) {:ok, user} {:error, message}
Gatekeeper.create_a_token_to_confirm_the_email(conn, user) {:ok, token} 
Gatekeeper.verify_the_token(conn, token) 
Gatekeeper.create_a_reset_password_token ......

And let the dev build around those functions. But actually, it's not that clear.

**Comment by danschultzer** [comment]
@abartier thanks for the feedback!

1. For a lot of this, I think it may just be documentation that's lacking. I've used Pow for several projects now that varies greatly in scope, and am pretty confident in the general structure now. Most of the methods that you would look for (with the Gatekeeper example) can be found in the `Pow.Plug` method calls.

I think the weakest part of Pow is extensions. I would prefer if it could be done in a similar way to plugs, but Pow works with several different domains (ecto/database, plug/connection and phoenix/views), while plugs only has to care about transforming the connection and that's it.

2. I don't think it's a good idea to transform this, because the user struct is used for forms, and ecto method calls. However, If you really want to transform it, then it's possible with a plug:

```elixir
# endpoint.ex

defmodule MyAppWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :my_app

  # ...

  plug Plug.Session,
    store: :cookie,
    key: "_my_app_key",
    signing_salt: "secret"

  plug Pow.Plug.Session, otp_app: :my_app

  plug MyAppWeb.SecureCurrentUserPlug

  # ...
end

# secure_current_user_plug.ex

defmodule MyAppWeb.SecureCurrentUserPlug do
  @spec init(any()) :: any()
  def init(opts), do: opts

  @spec call(Conn.t(), any()) :: Conn.t()
  def call(conn, _opts) do
   case conn.assigns do
     %{current_user: current_user} ->
        filter(current_user)

     conn ->
       conn
  end

  defp filter(user) do
    # filter some values
  end
end
```

This is in general what I want developers to do. Pow is built to make developers think about data transformation, and having clear separation of responsibility. `Pow.Plug` and `Pow.Phoenix` method calls transforms plug connection. `Pow.Ecto` method calls transforms a user struct or ecto changeset.

`Pow.Plug` will be the closest to a general interface for most. It could be used with Raxx instead of Phoenix, but it still expects a plug connection. You may have an app that doesn't use plug, and you only want to use `Pow.Ecto` method calls.

Does this gives you a better understanding, and something that should be explained in better details in the documentation?

**Comment by abartier** [comment]
@danschultzer thanks, yes it helps a lot and gives me a better understanding. 
For the documentation, I'm on it too. I'll try to contribute to it as much as I can.

**Comment by danschultzer** [comment]
There has been a lot of changes to Pow since this, and Pow has become stable since the `1.0.0` release! I'm working on improving how extensions are working in #82 which ideally would make it all feel like plug transformations.

Thanks for the discussion, it helped shape a lot of the documentation. Please reply, or open new issue if you got other feedback!
