### ISSUE TITLE
Bearer token to start session, Session thereafter; working, but feedback requested

### ISSUE THREAD

**Issue by sensiblearts** [danschultzer/pow#154]
Greetings,
The following is working, but I would appreciate any suggestions if you're interested and have time.

I have a flutter (native mobile) app that uses `Phoenix.Token.verify` to allow access to the API.

Also, I have a Webview in the flutter app that uses the same (API) Bearer token to initiate a session; then after initated, it uses Pow.Session.

Any feedback on pipes, controller logic is appreciated:

```elixir
  pipeline :native_token do
    plug GjwappWeb.Plug.ApiAuth # using Bearer token instead of session
    plug :accepts, ["html"]
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug GjwappWeb.Plug.NativeLayout
  end

  pipeline :native do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug GjwappWeb.Plug.NativeLayout
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  # The first time the flutter app hits the router, we go here:

  scope "/nm", GjwappWeb do
    pipe_through [:native_token]  
    get "/gallery_session", NmGalleryController, :index, as: :gallery_session_path
  end

  # and once session is initiated (above scope), use session instead of token:

  scope "/nm", GjwappWeb do
    pipe_through [:native, :protected]
    resources "/galleries", NmGalleryController
  end

### and then the NmGalleryController code for this is:
 
  def index(conn, _params) do
    userid = conn.assigns[:current_user_id] # Bearer token Plug assigns this
    if userid do # passing Bearer token
      user = Users.get_user!(userid)
      config = Pow.Plug.fetch_config(conn)
      {conn, user} = Pow.Plug.Session.create(conn, user, config)
      galleries = Galleries.list_galleries() # ignore user for now
      conn
      |> Pow.Plug.assign_current_user(user, config)
      |> render(:index, galleries: galleries)  
    else # using Session
      user = conn.assigns.current_user
      galleries = Galleries.list_galleries()
      conn
      |> render(:index, galleries: galleries)  
    end
  end

```
This seems to be working fine, but please let me know if I'm doing something weird.
DA

**Comment by danschultzer** [comment]
This looks fine, but you could skip the session plug entirely and only depend on `Phoenix.Token`. In the readme there's an example with Guardian, but it's the same setup with `Phoenix.Token`: https://github.com/danschultzer/pow#authorization-plug

This would probably make your flow much cleaner since you can just leverage the pow plug authenticate method to create token.

**Comment by sensiblearts** [comment]
Thanks! for the speedy reply.  I think I have to use sessions because I'm combining all 3 parts into one phoenix app:

1) html app served to browser  (templates/layout/app.html.eex -- includes `<nav>` section)
2) json api to flutter
3) subset of html served to flutter Webview (templates/layout/native.html.eex -- no `<nav>` section)

Users can register or sign in at (1) or (2).  And I'm trying to reuse as much code as I can between (1) and (3).

So, to reuse this part of index.html.eex:

```elixir
 <%= link "Show", to: Routes.nm_gallery_path(@conn, :show, gallery) %>
```
I would have to figure out how to make [flutter_webview_plugin](https://pub.dartlang.org/packages/flutter_webview_plugin) use the token when navigating. It seemed simpler to reuse the session code that was already working for the browser web app.

(FYI, the [flutter_webview widget](https://pub.dartlang.org/packages/flutter_webview) does **not** yet work with the mobile keyboard. I had to switch to [flutter_webview_plugin](https://pub.dartlang.org/packages/flutter_webview_plugin) widget.

**Comment by danschultzer** [comment]
Oh, I see. Your solution works, and I think it's good as it is. I haven't worked with flutter webview so I don't know if it makes sense to have token based auth rather than session for it.

If token based auth is more appropriate than session for flutter webview, you could separate the routes into API and frontend routes, where the pipeline for frontend routes as the session plug, and the pipeline for API routes has the custom `Phoenix.Token` plug. You can still serve the subset HTML that way and keep it token based for the API (you are not required to put the session plug in the `endpoint.ex`, it can be inside any pipeline).

**Comment by danschultzer** [comment]
Also you can refactor the code by calling` Pow.Plug.Session.do_create/3`:

```elixir
      conn
      |> Pow.Plug.Session.do_create(user, config)
      |> render(:index, galleries: galleries)  
```

It'll assign the current user for you.
