### ISSUE TITLE
JWT Auth does not work

### ISSUE THREAD

**Issue by Immortalin** [danschultzer/pow#170]
https://github.com/Immortalin/pow_token_auth_test, using the README instructions.

**Comment by danschultzer** [comment]
You also need to set up Guardian as you usually would do. In this case session setup should work, so just add the following to your `endpoint.ex` (before `Test.Pow.Plug`):

```elixir
plug Test.Guardian.Plug.VerifySession
plug Test.Guardian.Plug.LoadResource, allow_blank: true
```

I haven't worked with Guardian personally, and I'm thinking of switching to an example with just `Phoenix.Token`. Then it'll be a self contained module that can just be added without any extra setup 😄

**Comment by Immortalin** [comment]
If you can do Phoenix.Token that would be perfect. Currently I have to use Guardian.DB for token revocation so might as well just stick everything in Mnesia. Tried adding JSON support to the controllers and session.ex plug but no luck as the code was _way_ too abstract. Out of curiosity, why was it designed that way?

**Comment by danschultzer** [comment]
It's to make it easier to integrate controller callbacks with all the extensions. The [pow controller macro](https://github.com/danschultzer/pow/blob/master/lib/pow/phoenix/controllers/controller.ex) has some docs on how it works, and there is some info in the [readme](https://github.com/danschultzer/pow#phoenix-controllers).

An action is divided into two pieces (process and response) but in the end it works just like a normal controller action. The pow controller macro connects the [two methods and handles callback](https://github.com/danschultzer/pow/blob/a8c018f34b84a5571dbfdd9855a0a8befc3e42e9/lib/pow/phoenix/controllers/controller.ex#L92-L110).

**Comment by danschultzer** [comment]
I think the extensions setup probably makes an easy switch to JSON response impossible. An API should be idempotent while a web interface isn't. The HTML web interface should redirect while the API should return errors.

I've focused on making Pow plug n' play for a HTML web interface. In the back of my head I've been thinking of API integration, but I do think that any API integration should require the developer to take control of the flow (so e.g. enabling extensions would mean to write some code to change the flow, and all routes has to be explicitly defined rather than using a macro).

I'm not sure if the existing controllers can be leveraged in this case. Pow controllers are pretty simple since they usually only consists of one plug method call and then handling response. However there is some assumptions made that probably can't be translated into an API setup.

Hopefully the coming week I'll have enough time to go through this and at least have a guide ready for API integration 😄

**Comment by danschultzer** [comment]
Added `Phoenix.Token` example to readme here: https://github.com/danschultzer/pow/blob/phoenix-token-example/README.md#authorization-plug

**Comment by Immortalin** [comment]
@danschultzer wasn't able to get Guardian working even with the additional plug. Phoenix.Token works perfectly, sent a pull request to fix some bugs. Also ` token = get_token_from_session(conn)` isn't called so removed.

**Comment by Immortalin** [comment]
Any plans for Mnesia integration à la `Guardian DB` for `Phoenix.Token`?

**Comment by Immortalin** [comment]
Now I just have to figure out the controller side of things 😝

**Comment by danschultzer** [comment]
Thanks!

You should be able to use the Mnesia store for tokens without [too much work](https://github.com/danschultzer/pow/blob/master/lib/pow/store/base.ex), but I don't have any plans since this is mostly meant as a demonstration for how to set up a custom custom authentication plug with Pow rather than a guide on API setup.

The custom controller guide should make it easy to set up the API controllers: https://github.com/danschultzer/pow/blob/master/guides/CUSTOM_CONTROLLERS.md

I agree with your points on common API use case. There may be some things I can add to Pow to DRY up a lot of the work required to set Pow up with an API.
