### ISSUE TITLE
How to make invited user part of a many-to-many relationship?

### ISSUE THREAD

**Issue by khaledh** [danschultzer/pow#179]
My app has a many-to-many relationship between users and organizations. The owner of an organization can invite new users to join their organization, which should result in adding both a new `User` record, as well as a `OrgMembership` record (representing the relationship between a user and an org).

In the [example](https://github.com/danschultzer/pow/blob/master/lib/extensions/invitation/README.md#parent-organization-or-team) under `PowInvitation`, it shows how to do that in the case a user belongs to one organization (which just sets the `organization_id` field in `invite_changeset/3`). But it's not clear to me how to make this work for many-to-many relationships.

**Comment by danschultzer** [comment]
You have to do it how you otherwise would update/create many-to-many [associations with ecto](https://hexdocs.pm/ecto/Ecto.Changeset.html#module-associations-embeds-and-on-replace).

You can either cast it from the form params (e.g. as a hidden field in the invite form) or you can use the invited by user to look up the organization:

```elixir
defmodule MyApp.Users.User do
  # ...

  def invite_changeset(user_or_changeset, invited_by, attrs) do
    user_or_changeset
    |> pow_invite_changeset(attrs)
    |> changeset_organization(invited_by, attrs)
  end

  # Use put_assoc with organization found from look up on the invited by user
  defp changeset_organization(changeset, invited_by, _attrs) do
    organization_id = get_organization_id(invited_by)
    org_memberships = [%OrgMembership{organization_id: organization_id}]

    Ecto.Changeset.put_assoc(changeset, :org_memberships, org_memberships)
  end

  defp get_organization_id(invited_by), do: # Some lookup based on the struct

  # OR use cast_assoc to use values given in invitation form
  defp changeset_organization(changeset, _organization, attrs) do
    changeset
    |> Ecto.Changeset.cast(params, [])
    |> Ecto.Changeset.cast_assoc(:org_memberships, with: &MyApp.OrgMembership.changeset/2))
  end
end
```

You would have to figure out what makes sense for your setup. Personally I would go for the first option since otherwise users can be invited to any organization (unless you add a validation that the invited by user has to be member of that organization too).

If a user can be the owner of several organizations, and the invited user should only be a member of one of them, then you would have to rethink this approach. In that case, I would try to ensure that the organization is loaded through the router pipeline, and then simply add it as a virtual field (e.g. `:current_organization`) to the user struct (using a plug to update the assigned `:current_user` with the organization).

There isn't any clear cut way of doing it, because there's so many possible ways of handling this.

**Comment by khaledh** [comment]
> If a user can be the owner of several organizations, and the invited user should only be a member of one of them, then you would have to rethink this approach.

This is exactly the case. I have the Ecto code for the creating the association figured out when a user creates a new org, but not when they invite another user to the same org, since the user creation in this case is completely handled by Pow, with no callbacks other than `invite_changeset/3`, which doesn't carry enough information about _which org_ the user was invited to. I'm also questioning whether `PowInvitation` allows the same user to be invited more than once simultaneously, one invitation per some context (in my case an org). Is that possible? Would it try to create a new user each time the user accepts the invitation? I feel this might need a fully custom flow for invitations in my case.

**Comment by danschultzer** [comment]
> This is exactly the case. I have the Ecto code for the creating the association figured out when a user creates a new org, but not when they invite another user to the same org, since the user creation in this case is completely handled by Pow, with no callbacks other than `invite_changeset/3`, which doesn't carry enough information about _which org_ the user was invited to

Yeah, it all depends on how your platform will work. I would probably do the above setup with a virtual field so e.g. something like this:

```elixir
defmodule MyApp.Users.User do
  # ...

  schema "users" do
    field :current_organization, :any, virtual: true

    pow_user_fields()

    timestamp()
  end

  # ...

  def invite_changeset(user_or_changeset, invited_by, attrs) do
    user_or_changeset
    |> pow_invite_changeset(attrs)
    |> changeset_organization(invited_by)
  end

  defp changeset_organization(changeset, invited_by) do
    org_memberships = [%OrgMembership{organization_id: invited_by.current_organization.id}]

    Ecto.Changeset.put_assoc(changeset, :org_memberships, org_memberships)
  end
end
```

```elixir
defmodule MyAppWeb.EnsureCurrentOrganizationPlug do
  # ...

  def call(conn, _opts) do
    org = conn.assigns[:current_organization]

    config = Pow.Plug.fetch_config(conn)
    user = %{Pow.Plug.current_user(conn, config) | current_organization: org}
   
    Pow.Plug.assign_current_user(conn, user, config)
  end
end
```

> I'm also questioning whether `PowInvitation` allows the same user to be invited more than once simultaneously, one invitation per some context (in my case an org). Is that possible? Would it try to create a new user each time the user accepts the invitation? I feel this might need a fully custom flow for invitations in my case.

It's not possible out of the box because the user is created when invited: https://github.com/danschultzer/pow/blob/b9885d0ab9d99e5e244a7ccc30fabdd5f55db109/lib/extensions/invitation/ecto/context.ex#L10-L18

The unique constraint on the e-mail field would be triggered. Since this is a many-to-many relationship, there is no way of to scope the constraint so you have to either:

1) Override the invitation create action to look up if there is an existing user invited, and add to the `:org_memberships`.
2) A full custom invitation flow rather than using PowInvitation.

PowInvitation extension has purposefully been made extremely basic because there is so many different ways of handling it. So far I think you can still use it for your setup, but at some point it'll probably make more sense to set up your own invitation logic and completely forego PowInvitation.

**Comment by khaledh** [comment]
@danschultzer Thanks for the detailed follow up.

> ```elixir
> defp changeset_organization(changeset, invited_by) do
>   org_memberships = [%OrgMembership{organization_id: invited_by.current_organization.id}]
> ```

Since the inviting user can have multiple orgs, it's not clear how `invited_by.current_organization` would be set at invitation accept time; which org would `current_organization` designate? This is only known at invitation time, but there's no where to persist it across the flow.

> The unique constraint on the e-mail field would be triggered.

That's what I also figured. This probably requires a separate table for invitations, where the unique key would be a combination of the user email and the org id being invited to (and maybe a role as well).

> PowInvitation extension has purposefully been made extremely basic because there is so many different ways of handling it.

Agreed. I think I'll need my own invitation logic given the requirements I have.

Thanks for the prompt response!

P.S. Great library btw. Finally I don't have to reimplement user registration/authentication every time I start a new project!

**Comment by danschultzer** [comment]
> Since the inviting user can have multiple orgs, it's not clear how `invited_by.current_organization` would be set at invitation accept time; which org would `current_organization` designate? This is only known at invitation time, but there's no where to persist it across the flow.

The `invite_changeset/3` is called when inviting, not when invitation is accepted. The user is already created when they have been invited. So you got access to the current organization there.

> I think I'll need my own invitation logic given the requirements I have.

Yeah, you would have the best control this way. It only makes sense to use `PowInvitation` if the user can only be invited once per email/user id.

> P.S. Great library btw. Finally I don't have to reimplement user registration/authentication every time I start a new project!

Thanks! Please feel free to open any issues or PR's to help improve Pow 😄

**Comment by khaledh** [comment]
> The `invite_changeset/3` is called when inviting, not when invitation is accepted. The user is already created when they have been invited. So you got access to the current organization there.

Ah, for some reason I missed that detail. Hmm, this means the associated membership record would also be created upfront at invitation time. This makes those tables (`Users` and `OrgMembership`) have non-fully registered users/memberships, which I have to filter in other places of the app. That complicates things for my case, so it confirms the fact that I'd rather not delegate this to `PowInvitation` and go my own way here.

Thanks again!
