### ISSUE TITLE
Authenticate as anonymous user?

### ISSUE THREAD

**Issue by owenstrevor** [danschultzer/pow#181]
Hello, is there a way to use Pow to track users who are not registered or logged in as essentially Anonymous users? Is there an identifier Pow provides one could use for this?

This would be really useful for tracking anonymous users with Presence in a social app.

**Comment by danschultzer** [comment]
Pow doesn't provide any method but I don't think it's needed because you can use the plug session that's set by default (this is the way logged in users are tracked as well). You can set an id with `Plug.Conn.put_session(conn, :uuid, uuid)` and fetch it with `Plug.Conn.get_session(conn, :uuid)`. You just have to adjust it for when users are logged in or not. I haven't used Presence so there may be better ways of doing this.

**Comment by owenstrevor** [comment]
Thanks for the fast and helpful response as always @danschultzer !

I think this should work; will play around with it and report my results back.
