### ISSUE TITLE
Question around User data in session becomes out of sync with data in db. 

### ISSUE THREAD

**Issue by joshchernoff** [danschultzer/pow#183]
Just an observation, but I was noticing that the current_user in my open session was not reflecting what changes I had made to it directly in the db. IE I flipped an admin boolean to true and then navigated to a controlled route and noticed I was still seeing my current user with a flag of false. I assume that is because the user is stored in cache somewhere to reduce the db hits on every request. I'd like to confirm if that is true and also what strategies you have in mind around user data discrepancies like I just pointed out.

**Comment by danschultzer** [comment]
That is correct. The user credentials are stored in ETS or Mnesia upon sign in, and only refreshed on user update.

There are several ways to handle this, and I've written about it here: https://github.com/danschultzer/pow/issues/93#issuecomment-464770426

I would recommend loading the user on each request if a DB hit on every request isn't an issue. If it's to verify certain user data, then it definitely should be loaded from DB on those requests rather than depending on the cached credentials.

**Comment by danschultzer** [comment]
I believe the above answers your question, I'll close this issue for now 😄
