### ISSUE TITLE
PowInvitation route issue when limiting invitation by role

### ISSUE THREAD

**Issue by humancopy** [danschultzer/pow#198]
When following the instructions to [limit invitation based on role](https://github.com/danschultzer/pow/blob/master/lib/extensions/invitation/README.md#limit-invitation-based-on-role) on Phoenix 1.4 it throws the following warning:

```warning: this clause cannot match because a previous clause at line 2 always matches```

This is because ```lib/extensions/invitation/phoenix/router.ex``` tries to define ```[:new, :create, :show]``` after they've been defined already in the protected route. One way to circumvent this is by putting the protected route under a different scope.

I think though it might be better to offer some kind of a solution either by trying to detect that the route was already defined or maybe passing some option in the config?

**Comment by danschultzer** [comment]
Yeah, that's true. Good catch.

I could update the readme to remove `, as: "pow_invitation"` so there is no conflict. This is how the lock users guides explains overriding the reset password route: https://github.com/danschultzer/pow/blob/79842ead4a6f9d7ecccfbe7689f9acfd67190ef9/guides/LOCK_USERS.md#optional-powresetpassword

The downside is that there will be two different routes this way with the same URI.

I could filter the routes by looking up the `:phoenix_routes` module attribute. I already filter [this for Ecto](https://github.com/danschultzer/pow/blob/b66912f02f14a24f8f715d6a59bf57bc84a709d5/lib/pow/ecto/schema.ex#L189-L193), but with routes it would probably requires some work since I use the `resources` macro extensively. This would be cleaner.

**Comment by humancopy** [comment]
Yeah I guess changing the ```as``` would be the fastest solution but then as you mentioned it will create the extra routes...

Checking ```:phoenix_routes``` for existing routes would be the cleanest way to resolve this. If you have an idea how to tackle this and would like to give me some guidelines I'd be happy to help implementing 😄

**Comment by danschultzer** [comment]
Just added a quick WIP in #199. Have to think about it before I commit to this approach, so please let me know if you got any feedback.

**Comment by humancopy** [comment]
Looks like the right direction to me, well done for cracking up this code so quickly! 😄
