### ISSUE TITLE
Security implications of using GET request to confirm-email

### ISSUE THREAD

**Issue by stuartbain** [danschultzer/pow#206]
The current mechanism for confirming a user's email address uses a GET /confirm-email/:id request. Although it makes confirmation a one click operation, I think it may be a security risk according to this Stack Exchange answer:

[What should a verification email consist of:](https://security.stackexchange.com/a/197005)

> You should make sure the verification page actually renders (not just that a GET request occurred). Browsers such as chrome (and antivirus programs) often load URLs without the user explicitly clicking them as either a pre-fetch or to scan for security reasons.
> 
> That could result in a scenario where a malicious actor (Eve) wants to make an account using someone else's email (Alice). Eve signs up, and Alice received an email. Alice opens the email because she is curious about an account she didn't request. Her browser (or antivirus) requests the URL in the background, inadvertently activating the account.

Perhaps the GET /confirm-email/:id could render a page with a Confirm E-Mail button that submits a POST request to actually confirm the account?

**Comment by danschultzer** [comment]
It's a good thought, I was thinking about this too when I was creating the extension.

I came the conclusion that the scope of email confirmation is to validate that the email is valid, and the user can receive emails, but not to verify the account. This is why the extension is called `PowEmailConfirmation`.

Then there's the whole thing that email by default isn't secure and anything sent (url, tokens, password) should be considered exposed for proper security considerations. In this context, the scenario with a malicious actor becomes moot since with email we can't know who's who anyway (so we'll never be able to know if a click on the link was performed by the actual user).

The only thing we know is that the email was delivered. In this case I believe good UX is better, so it just be a link that redirects to the sign in screen. Less steps with no difference in security.

**Comment by stuartbain** [comment]
Thanks for the explanation Dan. The one-click UX is definitely better and upon further research I saw that Coherence and Devise (Ruby) also appear to use the GET method for confirmation.
