### ISSUE TITLE
Telemetry Error with Redix 0.10.2

### ISSUE THREAD

**Issue by axelclark** [danschultzer/pow#208]
I'm using pow 1.0.9 with redix 0.10.2.  I followed the Redis guide and when I run the tests I get the following error.  Any idea what the problem is?

```elixir
     ** (ArgumentError) argument error
     code: assert PowRedisCache.get(@default_config, "key") == :not_found
     stacktrace:
       (stdlib) :ets.lookup(:telemetry_handler_table, [:redix, :pipeline])
       /Users/jackclark/workspace/ex338/deps/telemetry/src/telemetry_handler_table.erl:47: :telemetry_handler_table.list_for_event/1
       /Users/jackclark/workspace/ex338/deps/telemetry/src/telemetry.erl:114: :telemetry.execute/3
       lib/redix.ex:758: Redix.pipeline_without_checks/3
       lib/redix.ex:563: Redix.command/3
       (ex338) lib/ex338_web/pow_redis_cache.ex:34: Ex338Web.PowRedisCache.get/2
       test/ex338_web/pow_redis_cache_test.exs:10: (test)
```

**Comment by danschultzer** [comment]
Away from the laptop but my hunch is that redix has not been started before running the tests. This is a shot in the dark, but maybe if you add the following to your `test_helper.exs` similar to how you start ecto:

```elixir
{:ok, _conn} = Redix.start_link(name: :redix)
```

If that’s not working then I’ll get back to this soon.

**Comment by axelclark** [comment]
Updating `test_helper.exs` returns the following error:
```elixir
** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.410.0>}}
```

I forgot to mention I don't receive the error with `{:redix, "~> 0.9.2"}`, only when I update to the latest redix version `{redix, "~> 0.10.2"}`.

**Comment by humancopy** [comment]
@axelclark I created a test app, added all your dependencies from `ex338` and still the tests pass when using `{redix, "~> 0.10.2"}` ... Something strange is going on with your app setup that I can't put the finger on 🤔

**Comment by axelclark** [comment]
@humancopy thanks!  It’s good to know it is within my app setup.

I’m guessing it has to do with how I’m passing options in to `Redix` in my `lib/ex338/application.ex`.  I will take a look later tonight.

**Comment by danschultzer** [comment]
You got pretty old app setup. You can fix this by updating your `application/0` method in `mix.exs` to use the `:extra_applications` option instead of `:applications`:

```elixir
  def application do
    [
      mod: {Ex338.Application, []},
      extra_applications: [
        :cowboy,
        :logger,
        :gettext,
        :phoenix,
        :phoenix_pubsub,
        :phoenix_html,
        :phoenix_ecto,
        :postgrex,
        :swoosh,
        :calendar,
        :phoenix_swoosh,
        :honeybadger,
        :scrivener_ecto,
        :runtime_tools
      ]
    ]
  end
```

Works for me when I set it up in your repo. You would have experienced the same issue if you upgrade to ecto 3.0. Most of the above apps can also be removed since they are automatically inferred (by default only `:logger` and `:runtime_tools` needs to be there).

This was a change in Elixir 1.4 (check the "Application inference" section): https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/

Might be a good idea to check the release notes up to 1.8 just to see if you got your app all up to date 😄

**Comment by axelclark** [comment]
@humancopy & @danschultzer thank you so much!  You both are great!
