### ISSUE TITLE
Add function logged_in?(conn)/1

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#25]
More than often, it's enough to check whether an user session is logged in or not.

But currently I can only check user via `current_user/1` which returns a bit heavy user-full struct.

How about add a new function returning lightweight `true/false` instead? This will make consuming less resource.

**Comment by danschultzer** [comment]
The idiomatic way of doing this in Elixir would be:

```elixir
# Using `current_user/1`
if Pow.Plug.current_user(conn) do

# Using `conn`
if conn.assigns[:current_user] do

# Using assigns in eex templates:
if @current_user do
```

I don't think a boolean return would consume any less resources. It would look something like this:

```elixir
def current_user?(%Plug.Conn{assigns: %{current_user: user}}) when not is_nil(user), do: true
def current_user?(_conn), do: false
```

But since the user struct already has been added to the connection, it won't do any difference. I recommend just using the if/else statements as it'll be fast pattern matching. It's would be the same as writing:

```elixir
case Pow.Plug.current_user(conn) do
  nil -> # Not authenticated
  _   -> # Authenticated
end
```

**Comment by jung-hunsoo** [comment]
I'm using `if Pow.Plug.current_user(conn) do` now, and I agree that `current_user?/1` will look like it.

What I think about the codes are like this;
```elixir
def current_user?(%Plug.Conn{assigns: assigns}), do: Map.has_key?(assigns, :current_user)
def current_user?(_), do: false
```

The `current_user/1` receives `conn` and returns `%User{}` whereas `current_user?` receives `conn` and returns `true/false` (5 bytes at most). In addition this is one of the frequently used function, I think.

**Comment by danschultzer** [comment]
Interesting. I'll test it out and see what way works better.

**Comment by danschultzer** [comment]
I do think having just `current_user/1` is sufficient. Returning the user struct won't use any more resources than pattern match and boolean response since it's immutable. It'll just be a reference, the bytes already are in memory.

There's some information here if interested:
https://elixir-lang.org/getting-started/basic-types.html
https://www.erlang-solutions.com/blog/erlang-19-0-garbage-collector.html
