### ISSUE TITLE
Limit login attempts 

### ISSUE THREAD

**Issue by emeidell** [danschultzer/pow#284]
This is likely related to #122 but not directly discussed.

I have found in that we are not limiting the amount of login attempts being made. This could make the apps vulnerable to brute force attacks. Though this could be added via extension it feels more appropriate to be included in the main build.

**Comment by danschultzer** [comment]
Good point!

When you say main build, I assume you mean that it should be part of this repo rather than a third-party library. I think having this as a built-in extension would be good (e.g. `PowRateLimiter`).

The rate limiter is documented in [NIST 800-63b](https://pages.nist.gov/800-63-3/sp800-63b.html#-5112-memorized-secret-verifiers) for passwords:

> Verifiers SHALL implement a rate-limiting mechanism that effectively limits the number of failed authentication attempts that can be made on the subscriber’s account as described in Section 5.2.2.

The minimum requirement is to [limit to 100 consecutive failed authentication attempts](https://pages.nist.gov/800-63-3/sp800-63b.html#throttle):

> When required by the authenticator type descriptions in Section 5.1, the verifier SHALL implement controls to protect against online guessing attacks. Unless otherwise specified in the description of a given authenticator, the verifier SHALL limit consecutive failed authentication attempts on a single account to no more than 100.
> 
> Additional techniques MAY be used to reduce the likelihood that an attacker will lock the legitimate claimant out as a result of rate limiting. These include:
> 
> - Requiring the claimant to complete a CAPTCHA before attempting authentication.
> 
> - Requiring the claimant to wait following a failed attempt for a period of time that increases as the account approaches its maximum allowance for consecutive failed attempts (e.g., 30 seconds up to an hour).
> 
> - Accepting only authentication requests that come from a white list of IP addresses from which the subscriber has been successfully authenticated before.
> 
> -Leveraging other risk-based or adaptive authentication techniques to identify user behavior that falls within, or out of, typical norms.
>
> When the subscriber successfully authenticates, the verifier SHOULD disregard any previous failed attempts for that user from the same IP address.

It should be relatively easy to build. I'm somewhat busy right now, so if anyone wants to start a PR on this, please feel free to tackle it. Also any discussion/ideas/feedback is welcome.

**Comment by emeidell** [comment]
Correct, by main build I was implying in this repo.

**Comment by danschultzer** [comment]
I made a PR to resolve this with #289 but as per discussion there I think Pow shouldn't deal with rate limiting at all. It's better handled at the gateway or proxy rather than application. I've created #290 with a production checklist that has a section on rate limiting.
