### ISSUE TITLE
Use "Post Redirect Get" Pattern

### ISSUE THREAD

**Issue by brajnacs** [danschultzer/pow#301]
Thanks for this awesome library, There is one small thing which I noticed that every POST request itself renders the templates (e.g on failed login, the same POST request renders the template with error messages).  

While this isn't a big deal but it would be great if that is changed to what we call "Post redirect get pattern" so that it will fix two small issues

- No-fuss on reloading the page (right now it submits the form again)

- Template rendering will be the responsibility of only one action (single source of truth)

**Comment by danschultzer** [comment]
PGR is used upon success, but I don't think it makes sense to do for invalid submissions. I think that would break semantics with REST? Also, I follow the Phoenix idiom where the invalid changeset generated from the action is used to render the form. Not sure how that could work with redirect since the changeset would then needs to be stored in the session.

**Comment by danschultzer** [comment]
I'll close this for now, but feel free to reopen.
