### ISSUE TITLE
Unhandled pattern matching in `delete_from_session_list/4`

### ISSUE THREAD

**Issue by szsoppa** [danschultzer/pow#302]
Hi, I recently received exception in `delete_from_session_list/4` function: https://github.com/danschultzer/pow/blob/c0c68e9c32e1e42b455710417e67c33972c2cc4e/lib/pow/store/credentials_cache.ex#L114

It seems like in this case we assume that `Base.get(config, backend_config, key)` will return a map with the user key. In my case, it returned `:not_found`, which is one of the possible return values https://github.com/danschultzer/pow/blob/c0c68e9c32e1e42b455710417e67c33972c2cc4e/lib/pow/store/credentials_cache.ex#L99

I'm using the master branch from this repo.

**Comment by danschultzer** [comment]
Oh, right, this exception highlights [the weakness](https://github.com/danschultzer/pow/pull/287#issuecomment-539762999) of the current setup in master. It really should be that keys can only be inserted or deleted, not updated.

The custom logic in the credentials cache wasn't used before I fixed it in #286, so I'm taking this opportunity to also make the cache store more efficient and Erlang friendly using [match specs](http://erlang.org/doc/apps/erts/match_spec.html).

I'm refactoring the whole cache store setup that I will try to finish before releasing `v1.1.14`: https://github.com/danschultzer/pow/compare/refactor-credentials-cache

It's a pretty heavy PR though, but I think it'll be worth it. It should be working out of the box if you're using ETS or Mnesia, but I'm working on keeping it backwards compatible so custom implementations like Redis cache will still work.

Since this bug only exists in master I think I'll wait till I can merge in the cache refactor rather than trying to fix the current setup.

**Comment by danschultzer** [comment]
Fixed in master

**Comment by szsoppa** [comment]
Thanks, @danschultzer!
