### ISSUE TITLE
API Guide after 1.0.14

### ISSUE THREAD

**Issue by mreishus** [danschultzer/pow#316]
After upgrading to 1.0.14, my API-based app couldn't register new users, and I couldn't fetch information related to users.  An update to the guide is probably needed.  After looking at the code, I made these minimal changes to make it work, I'm not very confident in them though (not confident enough to make a pullrequest):

**(API GUIDE)** inside **`api_auth_plug.ex`** -> `def create(conn, user, config) do`
old
```elixir
    CredentialsCache.put(store_config, token, user)
```
new
```elixir
    CredentialsCache.put(store_config, token, {user, []})
```

**(NOT IN API GUIDE, JUST MY APP)** `whatever_controller.ex` needs to get info about a user

old
```elixir
    user = Pow.Plug.current_user(conn)
```
new
```elixir
    {user, _metadata} = Pow.Plug.current_user(conn)
```

Register / login / email confirm / password reset via API all work after those changes.

**Comment by danschultzer** [comment]
Oh, sorry, completely missed that working on #304 and #287. Would have made it backwards compatible but since the release is out I'll just rework the API guide.

You should be able to get it working by using the following changes in this PR: #317

All changes are in the `APIAuthPlug`. In short, the only missing piece you needed was:

```diff
    |> case do
    |> store_config()
    |> CredentialsCache.get(token)
    |> case do
-      :not_found -> {conn, nil}
-      user       -> {conn, user}
+      :not_found        -> {conn, nil}
+      {user, _metadata} -> {conn, user}
    end
  end
```

Instead of changing `Pow.Plug.current_user(conn)`. The PR has some additional changes too that conforms more to the way Pow deals with the session stores now.

**Comment by mreishus** [comment]
Ok, thanks.  Checking out the PR.
