### ISSUE TITLE
Guides around integration testing

### ISSUE THREAD

**Issue by joshchernoff** [danschultzer/pow#325]
While I think it does not make sense to directly test the interface of pow, I do feel like testing integration of pow in an app in question is important. 

I was curious about your thoughts on this matter. 

How do you currently test the integration of pow? Is there a best practice on this? I typically try to stay away from acceptance tests due to the heavy requirement of a headless browser and tendency for being slow running.

**Comment by danschultzer** [comment]
This is enough for most use cases: https://github.com/danschultzer/pow#testing-with-authenticated-users

With #230 I aim to cover all custom setup with unit tests. Apart from that I don't think it's necessary to add any integration tests, since controller tests already will call Pow plugs, and Ecto tests will (likely) call the Pow changeset.

In most cases you should only test the logic in your app. There may be a few scenarios where you got some unique configuration of a third-party app that's vital. That's also why I try to force developers to configure Pow with code rather than handling it with config options, so it's much easier to identity what needs to be tested.

This might be interesting to see what a deeper dive with testing Pow on custom setup looks like: #311 sprung from https://github.com/danschultzer/pow/issues/271#issuecomment-534687467

**Comment by joshchernoff** [comment]
Very cool thanks for sharing the links.
