### ISSUE TITLE
I am using phone number as a user_id_field. Is it possible to use PowResetPassword, PowEmailConfirmation, PowInvitation?

### ISSUE THREAD

**Issue by Abat** [danschultzer/pow#336]
Or do they support email user_id_field only? I want to have same flow but with SMS.

If I can't reuse them, how should I best proceed? Writing my own extensions?

Please suggest best approach.

**Comment by danschultzer** [comment]
`PowInvitation` works without e-mail. It'll display a link though, so you might want to make a custom route for `POST pow_invitation_inivtation_path :create` so it can deliver an SMS (not sure if that is good practice though!).

I think `PowResetPassword`, if possible, should permit using alternative to email, such as SMS or even an authenticator. With the current version, you would have to write your own controller to handle it, but you can leverage the built-in Reset Password cache.

`PowEmailConfirmation` as the name suggests would always require email. It could be great to have some general `PowAccountConfirmation` that can be adjusted to any custom verification flow, but I think it'll be too difficult to implement since the DB columns have to make sense (e.g. `:unconfirmed_email` and `:email_confirmed_at`).

I would always recommend first just writing your own logic (controllers/ecto context), instead of extensions. Extensions only make sense if you want to release a library or need to reuse it in various parts of your project. If you do want to make extensions then there's a pretty good example here with CAPTCHA and rate limit lock out: https://github.com/danschultzer/pow/issues/324#issuecomment-555828694

Also I recommend that you create an issue for each extension you want to implement with SMS if you need specific help. It'll be easier for others to find and join in in the future rather than just one issue for everything.

**Comment by Abat** [comment]
> Also I recommend that you create an issue for each extension you want to implement with SMS if you need specific help. It'll be easier for others to find and join in in the future rather than just one issue for everything.

Got it, I will divide it into several issues.

> I would always recommend first just writing your own logic (controllers/ecto context), instead of extensions. Extensions only make sense if you want to release a library or need to reuse it in various parts of your project. If you do want to make extensions then there's a pretty good example here with CAPTCHA and rate limit lock out: #324 (comment)

I am going to start with custom controllers.

One question though: I still have an email field in my User model. I do use PowResetPassword, PowEmailConfirmation and PowInvitation with email.

If I want to add same functionality for phone_number, using custom controllers, can I still use extensions for email?

Or is it better to not mix them and write custom controllers for email too?

**Comment by danschultzer** [comment]
> If I want to add same functionality for phone_number, using custom controllers, can I still use extensions for email?

Yes, keep the extensions as it is now, and then you can adjust them as you figure out how the auth flow should work.

**Comment by ansh14j** [comment]
Is there any progress to support PowResetPassword with phone number.
