### ISSUE TITLE
Clarifying what controller callbacks are 

### ISSUE THREAD

**Issue by Abat** [danschultzer/pow#340]
```
def before_process(Pow.Phoenix.RegistrationController, :create, conn, config) do
    IO.inspect "I am here"

    conn
    |> Controller.put_flash(:error, "registration not allowed")
    |> Conn.halt()
end
```

@danschultzer  I want this code to prevent user from creating an account.

However, User is still created. I see the flash message, but connection is not halted.

Is my understanding of controller callbacks wrong?

**Comment by danschultzer** [comment]
You should return `{:halt, conn}` so the [Pow controller callbacks](https://github.com/danschultzer/pow/blob/v1.0.15/lib/pow/extension/phoenix/controllers/controller_callbacks.ex#L22) understands that it shouldn't continue passing the conn to other extensions, so:

```elixir
def before_process(Pow.Phoenix.RegistrationController, :create, conn, config) do
    IO.inspect "I am here"

    conn =
      conn
      |> Controller.put_flash(:error, "registration not allowed")
      |> Conn.halt()

    {:halt, conn}
end
```

But just a warning, controller callback should be the last option. The best way is to either control the conn flow with a plug, or alternatively attempt to deal with it in the ecto context. It depends on what you are trying to achieve, and in some cases there is no other option than hooking into the actual controller action with a callback.

**Comment by Abat** [comment]
> But just a warning, controller callback should be the last option. 

Could you please tell why? Why is it the last option?

**Comment by Abat** [comment]
```
def before_process(Pow.Phoenix.RegistrationController, :create, conn, config) do
    IO.inspect "I am here"

    conn =
      conn
      |> Controller.put_flash(:error, "registration not allowed")
      |> Conn.halt()

    {:halt, conn}
end
```

I get `no function clause matching in Pow.Plug.fetch_config/1` error.

`fetch_config` expects `conn`, not `{:halt, conn}`

**Comment by danschultzer** [comment]
> Could you please tell why? Why is it the last option?

Because it's not very explicit. If I could, then I would move all controller callback configuration to the endpoint or router so you can see the whole flow. Right now it's kinda a guess what actually happens, and in which order.

It's something that has been on my list for a long time: https://github.com/danschultzer/pow/issues/82

> 

> I get `no function clause matching in Pow.Plug.fetch_config/1` error.
> 
> 
> `fetch_config` expects `conn`, not `{:halt, conn}`

Ugh, case in point to the above. I thought I had made it possible to halt the connection, but it does just [expect the conn](https://github.com/danschultzer/pow/blob/master/lib/pow/phoenix/controllers/controller.ex#L105). Let me look at it with fresh eyes tomorrow and see how it can be best resolved. It should definitely handle `{:halt, conn}` responses, since that is something that gets handled in `Pow.Extension.Phoenix.ControllerCallbacks.before_process/4`.

Also, could you explain what this extension/controller callback is supposed to do. When is it you want to prevent registration? There may be a more explicit way of handling it.

**Comment by Abat** [comment]
> Because it's not very explicit. If I could, then I would move all controller callback configuration to the endpoint or router so you can see the whole flow. Right now it's kinda a guess what actually happens, and in which order.

I see now.

I am trying to have logic similar to PowEmailConfirmation, but for phone numbers. Related to #336 

Now instead of controller callbacks I am using Users context and User model.

```
def authenticate(params) do
    user_id = params["user_id"]
    password = params["password"]

    user_id
    |> get_by_user_id()
    |> current_phone_number_unconfirmed?()
    |> maybe_verify_password(password)
  end
```

Using `current_phone_number_unconfirmed?()` I am able to stop users with unverified phone numbers from signing in.

However, they get automatically signed in right after registration. 

```
def create_user(conn, params) do
    config = fetch_config(conn)

    params
    |> Operations.create(config)
    |> maybe_create_auth(conn, config)
  end
```

In `Pow.Plug`  `maybe_create_auth(conn, config)` is creating a session and I don't know how to stop it.

I don't want to write custom controllers since I want to use existing extensions for sign up/login with email.

**Comment by danschultzer** [comment]
I would first implement that as a plug, before setting up an extension. You probably also want to send a confirmation number to input rather than a link in the SMS? For that you should set up controller to handle phone confirmation.

Here's an example of how you can interrupt the auth flow if they haven't confirmed their phone number (based on https://github.com/danschultzer/pow/issues/318#issuecomment-552608811, I recommend checking that out for example how to adjust the auth flow):

```elixir
defmodule MyAppWeb.RequirePhoneConfirmationPlug do
  @moduledoc """
  This plug ensures that a user has confirmed their phone number.

  ## Example

      plug MyAppWeb.RequirePhoneConfirmationPlug
  """

  alias MyAppWeb.Router.Helpers, as: Routes

  @doc false
  @spec init(any()) :: any()
  def init(opts), do: opts

  @doc false
  @spec call(Conn.t(), any()) :: Conn.t()
  def call(conn, _opts) do
    conn
    |> Plug.current_user()
    |> case do
      nil  -> conn
      user -> maybe_require_phone_confirmation(user, conn)
    end
  end
  
  defp maybe_require_phone_confirmation(%{phone_number_confirmed_at: nil}, conn) do
    conn
    |> Controller.redirect(to: Routes.phone_confirmation_path(conn, :new))
    |> Plug.Conn.halt()
  end
  defp maybe_require_phone_confirmation(_user, conn), do: conn
end
```

The above always redirects the user to `phone_confirmation_path/2` so they may input the number they received. They'll be signed in, but can't get any further until the phone number if confirmed.

You can also do it exactly the same way as `PowEmailConfirmation`; clear the session and redirect with an error message:

```elixir
  defp maybe_require_phone_confirmation(%{phone_number_confirmed_at: nil}, conn) do
    {:ok, conn} = Pow.Plug.clear_authenticated_user(conn)

    conn
    |> Controller.put_flash(:error, "Please confirm your phone number with the link send to you.")
    |> Controller.redirect(to: Routes.phone_confirmation_path(conn, :new))
    |> Plug.Conn.halt()
  end
  defp maybe_require_phone_confirmation(_user, conn), do: conn
```

Add `MyAppWeb.RequirePhoneConfirmationPlug` to your endpoint or in your protected pipeline in router.

**Comment by Abat** [comment]
> You probably also want to send a confirmation number to input rather than a link in the SMS?

Yes, of course.

> Here's an example of how you can interrupt the auth flow if they haven't confirmed their phone number (based on #318 (comment), I recommend checking that out for example how to adjust the auth flow):

Thanks a lot, I will be digesting this today.

> Also for the solution you did, the best way to handle it there would be:

```
def authenticate(params) do
    params
    |> pow_authenticate()
    |> case do
       %{phone_number_confirmed_at: nil} -> nil
       any -> any
    end
end
```

But this doesn't stop authentication right after registration. You are signed in after registration. Once you log out and try to sign in, the above `authenticate` will prevent it, yes. But I want to prevent authentication right after registration.

In `Pow.Plug`  :

```
def create_user(conn, params) do
    config = fetch_config(conn)

    params
    |> Operations.create(config)
    |> maybe_create_auth(conn, config)
end
```

`maybe_create_auth(conn, config)` doesn't call `authenticate` in Users.

Thanks a lot, @danschultzer , I think I am very close to get this done.

**Comment by danschultzer** [comment]
> But this doesn't stop authentication right after registration. You are signed in after registration.

Yeah, it's best to handle it is with a plug or in controllers. The Ecto context doesn't know about auth sessions, so it's not the right place to deal with it
