### ISSUE TITLE
Customize Urls?

### ISSUE THREAD

**Issue by coladarci** [danschultzer/pow#341]
First off, thank you SO much for this library; a real treat to get up and running.

This feels like an obvious ask, and I did a lot of digging into the code and issue/pull history and I can't find any reference to it, so I thought I'd see your thoughts.

Out of the box you get all of this great functionality, but having customers see the RESTFUL URLs for Login and Registration is likely not going to fly versus user friendly things like "/login" and "/signup". Short of copy-pasting all of the inner implementation of `pow_session_routes` and `pow_registration_routes` w/ new paths for everything, is there a simpler, more maintainable way of doing this that anyone can think of? 

THANKS AGAIN!

**Comment by danschultzer** [comment]
Thanks!

Here's an issue with a reply answering your question: https://github.com/danschultzer/pow/issues/248#issuecomment-521225322

REST resource is used for the routes so the only way to deal with it is to override each route you wish a different path for (since if you use the resource macro then you'll just have `/login/new` instead of `/sessions/new`). In the above example, having the block with `pow_routes/0` after ensures fallback for any routes you don't customize. This will be the simplest and easiest way to maintain custom route paths.

**Comment by coladarci** [comment]
Thank you! If you are into it, I've added it to the docs https://github.com/danschultzer/pow/pull/342
