### ISSUE TITLE
relogin as another user

### ISSUE THREAD

**Issue by ehayun** [danschultzer/pow#355]
Its not an issue but I can't find an answer in any of the forums

How do I re-login as another user without know the password?
I want my admin to be able to login as another user. How do I do that

If its not the right place to put it, please, forgive me and delete this issue

**Comment by danschultzer** [comment]
The way I have usually done that is to set the privilege in the session and have a custom auth plug. I think that’s the most appropriate way of dealing with this, rather than actually log in a different user. The admin user session is still kept.

Auth controller:

```elixir
defmodule MyAppWeb.AdminController do
  use MyAppWeb, :controller

  alias Plug.Conn

  @spec auth(Conn.t(), map()) :: Conn.t()
  def auth(conn, %{"user_id" => user_id}) do
    conn
    |> Conn.put_session("auth_for_user_id", user_id)
    |> redirect(to: Routes.page_path(conn, :index))
    |> Pow.Plug.create_user(user_params)
  end
end
```

The plug:

```elixir
defmodule MyAppWeb.SuperUserAuthPlug do
  @spec init(Keyword.t) :: Keyword.t
  def init(default), do: default

  @spec call(Plug.Conn.t, Keyword.t) :: Plug.Conn.t
  def call(conn, _opts) do
    conn
    |> super_user_load()
    |> case do
      nil ->
        conn

     user ->
        config = Pow.Plug.fetch_config(conn)

        Pow.Plug.assign_current_user(conn, user, config)
    end
  end

  defp super_user_load(conn) do
    conn
    |> Pow.Plug.current_user()
    |> is_super_user?()
    |> case do
      true  ->
        conn
        |> Plug.Conn.get_session("auth_for_user_id")
        |> maybe_load_user()

      false ->
        nil
    end
  end

  end

  defp is_super_user?(%{role: “admin”}), do: true
  defp is_super_user?(_user), do: false

  defp maybe_load_user(nil), do: nil
  defp maybe_load_user(user_id), do: MyApp.Repo.get(MyApp.Users.User, user_id)
end
```

Put the plug for all non-admin routes.

The above is from the top of my head. You may wish to [encrypt the plug session](https://hexdocs.pm/plug/Plug.Session.COOKIE.html), since by default it can be read but not tampered.

The above makes the assumption that it’s the same endpoint. You may have an umbrella project where there’s an admin endpoint separate from the default web endpoint. You can read more here: https://powauth.com/guides/2019-09-12-multiple-schemas.html

**Comment by ehayun** [comment]
Thanks
It start to work. I have to do more stuff but this is the right path. 
:)
