### ISSUE TITLE
Redirect to different domain from after_sign_in_path

### ISSUE THREAD

**Issue by Ecksters** [danschultzer/pow#387]
I'm trying to get Pow to generate a JWT from the callback of a provider, then immediately redirect the user to an external URL with the JWT in the params.

It seems like after_sign_in_path is expecting a route within the application, is there a way to simply have it redirect to an external URL instead so I can skip the additional request?

**Comment by danschultzer** [comment]
Is this for [PowAssent](https://github.com/pow-auth/pow_assent)?

In any case it's not possible as you have to explicitly call `Phoenix.Controller.redirect(external: url)` instead of `Phoenix.Controller.redirect(to: path)` which is [used in the session controller](https://github.com/danschultzer/pow/blob/v1.0.16/lib/pow/phoenix/controllers/session_controller.ex#L44).

You should override the session controller create action:

```elixir
defmodule MyAppWeb.SessionController do
  use MyAppWeb, :controller

  alias Pow.Plug

  def create(conn, %{"user" => user_params}) do
    case Plug.authenticate_user(conn, user_params) do
      {:ok, conn} ->
        redirect(conn, external: "https://example.com?jwt=#{conn.assigns[:jwt]}")

      {:error, conn} ->
        changeset = Pow.Plug.change_user(conn, conn.params["user"])

        conn
        |> put_flash(:info, "Invalid email or password")
        |> render("new.html", changeset: changeset)
    end
  end
end
```

```elixir
defmodule MyAppWeb.Router do
  use Phoenix.Router
  # ...

  scope "/", MyAppWeb do
    resources "/session", SessionController, singleton: true, only: [:create]
  end

  scope "/" do
    pow_routes()
  end
end
```

If this is for PowAssent then you should override the `/:provider/callback` route instead.

**Comment by Ecksters** [comment]
Thanks, that answers my question!
