### ISSUE TITLE
Override the whole email generation logic

### ISSUE THREAD

**Issue by augnustin** [danschultzer/pow#427]
I have a custom behavior on email generation in my app.

I'd like to plug it with Pow, though I'm not sure how to achieve that.

I tried to have a custom `Mailer`:

```
defmodule Vae.PowMailer do
  require Logger
  def cast(email) do
    MyApp.Mailer.build_email(:template, :service, email.user, Map.extend(%{
      subject: email.subject,
    }, email.assigns))
  end

  def process(email), do: MyApp.Mailer.send(email)
end
```

But I need to set the `:template` name, which, unfortunately, is not available within the `Email`. I could try to deduce it from the rendered `%Email{}` but this would be very suboptimal.

Instead of a `Mailer`, my feeling is that I should override [`send_confirmation_email(user, conn)`](https://github.com/danschultzer/pow/blob/726c1d9219bee7df1046e2ec6a17f413b2ce8397/lib/extensions/email_confirmation/phoenix/controllers/controller_callbacks.ex#L128) or `Mailer.email_confirmation(conn, unconfirmed_user, url)`.

How can I achieve this?

Thanks

**Comment by Schultzer** [comment]
Remember to add the :put_pow_mailer_layout to your pipeline.

Something like this 

```elixir
pipeline :browser do
....
  plug :put_pow_mailer_layout, {MyAppWeb.EmailView, :layout}
....
end
```

**Comment by danschultzer** [comment]
If you mean that you just need to set a custom layout, then what @Schultzer writes is the thing you have to do. There's more in the docs here: https://hexdocs.pm/pow/1.0.18/Pow.Phoenix.Mailer.Mail.html#module-custom-layout

But if you mean that you need to override how the mails are processed/rendered then you have to set up custom view modules. What is it that `Vae.Mailer.build_email/3` does?

**Comment by augnustin** [comment]
Hey!

Thanks again for support. You guys have the same same, is that fortuitous? :smile: 

`build_email` does pretty much the same as `PowMailer.cast\1`:

```
  def build_email(template_name_or_id, from, to, params) do
    %Email{}
    |> to(format_mailer(:to, to))
    |> from(format_mailer(:from, from))
    |> custom_id_if_present(Map.get(params, :custom_id))
    |> attach_if_attachment(Map.get(params, :attachment))
    |> render_body_or_template_id(template_name_or_id, params)
  end
```

And `send` is pretty much `PowMailer.process\1`.

But of course I have a different interface.

For now, I wrote:

```
  def cast(email) do
    MyApp.Mailer.build_email(subject_to_template(email.subject), :service, email.user, Map.merge(%{
      subject: email.subject,
      name: MyApp.User.fullname(email.user)
    }, Enum.into(email.assigns, %{})))
  end

  def process(email), do: Vae.Mailer.send(email)

  defp subject_to_template(subject) do
    case subject do
      "Confirm your email address" -> "user/confirmation.html"
      "Reset password link" -> "user/password.html"
    end
  end
```

But this is clearly not optimized and not robust to changes.

Hence I'd rather override `send_confirmation_email(user, conn)`, and I would kind of expect to put it in `Pow.UserEmail` like I did with coherence:

```
defmodule MyApp.Coherence.UserEmail do
  def confirmation(user, url) do
    Mailer.build_email(
      "user/confirmation.html",
      :service, user, %{
        subject: "Confirmation de mon compte",
        url: url,
      }
    )
  end
end
``` 

Can I do something like this?

**Comment by danschultzer** [comment]
> You guys have the same same, is that fortuitous?

If you mean last name, yeah, we're related 😄 

> Can I do something like this?

With custom controllers or views it's possible. The mailer in Pow works the same way as Phoenix templates, so it's the same way you would customize it. To customize all at once, you have to override the logic in the `mailer_view` method, replicating the `Phoenix.View` macro. This means writing custom `render/2` methods.

The alternative is to set up custom controllers.

However, I would take a step back first and see if you really need that setup for Pow e-mails. You can generate the mailer templates with `mix pow.extension.phoenix.mailer.gen.templates` and customize them there. Then, if needed, you can call `custom_id_if_present/2` and `attach_if_attachment /2` in the view helpers. While I understand the desire to streamline the mail process to your current flow, I would be advise to only do it if absolutely necessary since you have to jump through several hoops to get there.

**Comment by augnustin** [comment]
Thanks for you feedback. 

I definitely need to use my own mail generation logic as it:
- makes sure emails are filtered in dev/staging environment to avoid spamming
- renders markdown written emails so that non-tech team can edit it's content
- applies some user formatting
etc.

Shouldn't we consider having a simpler way to plug a custom mailer into Pow, without having to rewrite the controller, which content doesn't need to change in this case.

**Comment by danschultzer** [comment]
> Shouldn't we consider having a simpler way to plug a custom mailer into Pow, without having to rewrite the controller, which content doesn't need to change in this case.

You a mixing two separate concerns, render and mail delivery. You got full control over mail delivery and can set it up any way you like. Render works the same way as you would render templates in Phoenix, and as I wrote you can ultimately set up custom `render/2` method in the `mailer_view` macro if you would like to take full control over the render flow.

But if you wish to combine the two concerns, as done in your example, that's when you need custom controller. This would be akin to combining Phoenix template and Plug send_resp logic in one.

There are no convention for mailer since Phoenix doesn't include one, but I decided to make the logic work the same way as how Phoenix works.

> makes sure emails are filtered in dev/staging environment to avoid spamming

You would normally set this as a config setting for the mailer adapter rather than coded logic.

> renders markdown written emails so that non-tech team can edit it's content

This can be done by just using the default Phoenix render logic the same way you would render a HTML page using markdown template. Alternatively a partial could be used.

> applies some user formatting

Likely something you want to handle in the view, not in mailer. But I would handle [preflight](https://github.com/danschultzer/premailex) in the mailer to ensure it can be delivered.
