### ISSUE TITLE
Refresh current user

### ISSUE THREAD

**Issue by augnustin** [danschultzer/pow#437]
Shouldn't there be a plug that refreshes the data stored in `:current_user`?

Something like:

```
  def refresh_current_user(conn) do
    config = fetch_config(conn)
    user = current_user(conn, config)
    assign_current_user(conn, Operations.get_by(id: user.id), config)
  end
```

Not sure if `Repo.get()` or `Repo.get_by(:id,)` should be preferred.

Otherwise, once logged in, if a user changes its name, it is not changed in the navbar until next session...

**Comment by Schultzer** [comment]
You can easily do this in your pipeline in your router.

Pow doesn't know about your user table and how you use it in your application.

**Comment by danschultzer** [comment]
If you use the default Pow registration controller to update the user then the cached credentials do get updated, but for custom logic you need to decide how you load the data. Reload logic is described in the docs: https://hexdocs.pm/pow/1.0.18/sync_user.html#content

**Comment by augnustin** [comment]
Thanks for the reference! 

I'll do what you suggest, though I'm still unsure of why this can't be a utility function of `Pow`.

> Pow doesn't know about your user table and how you use it in your application.

The example code I submitted above never uses a reference to the `User` model either. Besides, `Pow` did know how to load the `current_user` in the first place, why couldn't it refresh it afterwards?

For instance if the unique key is the email, then it could refresh itself with a `get_by(:email,)`, couldn't it?

**Comment by danschultzer** [comment]
I believe what @Schultzer meant is that the above logic assumes that the user table has `id`. You should instead call:

```elixir
config = [otp_app: :my_app]

user
|> Pow.Operations.fetch_primary_key_values(config)
|> Pow.Operations.get_by(config)
```

> I'll do what you suggest, though I'm still unsure of why this can't be a utility function of `Pow`.

I don't think it would offer much value, and might actually be make it more difficult to read/understand (like the above). I prefer if you just call `Repo.get(user.id)` in a plug method.

**Comment by augnustin** [comment]
Hum, I disagree with you.

A utility function is there is the user needs it, and it won't bother anyone who doesn't. Besides, I first find surprising to have to actually refresh the `current_user`, I never faced this situation in any other framework (because it is fetched on every request, which is not optimal of course), so having a utility function for this would mean to me

> Yeah that's something that happens, it's not a bug, come on do it!

The simple fact that you need to mention it in the doc, means there is a usage to the function.

In general, your great support is very helpful, but I'm not a big fan of most of the solution you offer, which is to make a custom `plug`: for me the authentication layer should be in the lib (`pow`), and the rest of the code shouldn't mix with it at any point, except maybe some extra config.

While in this case, the `refresh_current_user` would have to be in the codebase.

**Comment by Schultzer** [comment]
@augnustin I understand that you are migrating away from coherence. 

Before @danschultzer build Pow, we where using coherence too, which gave us way too much in the box and way to little flexibility to extend.

> A utility function is there is the user needs it, and it won't bother anyone who doesn't. Besides, I first find surprising to have to actually refresh the current_user, I never faced this situation in any other framework (because it is fetched on every request, which is not optimal of course), so having a utility function for this would mean to me

I'm not sure what the goals are for other frameworks but, I believe that when it comes to security then you should own your code (which also increase maintainablity).

>  so having a utility function for this would mean to me

I would disagree half way here. This is something that could be impl. in the future when the scope is more known and it wont be at a cost on security, performance and maintainability.

Pow make it easy for you to own your code (extension/plug) or leverage maintained code (builtin features).

If you are seeking a more maintained version of coherence then, I think your only option is to fork it and deal with the open issues and security concerns yourself.

**Comment by danschultzer** [comment]
@augnustin I get what you are saying, but this is where Elixir coding convention usually takes a different and in my opinion better approach than many other languages. It makes you take ownership of your code instead of abstracting logic unnecessarily. And I believe this is the best option for business logic like this as it's very context specific whether you need to reload the user or not and in what way. There is no one way of doing it. Adding such helper to Pow would add more code and maintenance than for the equivalent implemented in the app.

So I opted to write a guide to show the different approaches you can take and decide what is better for your setup.

If it was practical, I would probably have removed most helpers in Pow, e.g. `pow_changeset`. IMO auth libraries should be more of a scaffold than framework. This is something I try to balance in Pow. I would be happy if most developers with time will peel most/all of Pow off in their platforms to have their custom auth setup.

I believe an identity provider may be a better fit for the concern you are describing.

All of this is not to say that the current way credentials cache work couldn't be improved. There are definitely issues working with DB records that may go stale, but so far this is the best I've come to.

**Comment by augnustin** [comment]
Interesting discussion here.

I understand your points though I have several comments:

> IMO auth libraries should be more of a scaffold than framework.

It seems to me this is true for a lib like `comeonin`, but not for `pow`: either this is full backend/plug logic, and all the mailing/view rendering/alert messaging logic is left to the user or it is handled by the lib like in `pow` and in that case it should come with a set of tools.

To compare with Rails, I think `pow` (and `coherence`) and the [`devise`](https://github.com/heartcombo/devise) of rails, while `comeonin` is the [`warden`](https://github.com/wardencommunity/warden), which one doesn't want to use, unless **very specific** requirements.

> I believe that when it comes to security then you should own your code (which also increase maintainablity).

Oh god no! Security is a hard topic, and if each developer should write his own authentication method, the web would be totally insecure. Which is why there are standards and libs. As a dev, I don't want to bother thinking if this password reset process is safe or not, I want to plug it, and that's it.

> I believe an identity provider may be a better fit for the concern you are describing.

Not sure what you mean by identity provider. 

I have had very good experience integrating [devise](https://github.com/heartcombo/devise), so that would be my source of inspiration if it were for me to maintain my authentication lib.

As a conclusion, I would still add the helper IMHO. :smile:

**Comment by danschultzer** [comment]
Jose being one of the authors of devise didn't port it to Elixir, and has commented that devise was a mistake that shouldn't be repeated. A black box auth solution should be working in isolation rather than being implemented into the app. This is commonly an [identity provider](https://en.wikipedia.org/wiki/Identity_provider).

Security is only as good as your implementation regardless of how much you offload to a library, and the best thing Pow can do to offer good security practice is to force developers to justify additional logic by coding it themselves. This is the reason for all the docs, that I only add helpers to Pow when I deem it absolutely necessary, and why I'm eager to remove many existing ones.

The job of Pow is not to carry your business logic, but to provide secure defaults that you can build on top of. To make the transition easier, Pow does a lot out of the box so you can focus on more pressing needs in your business logic, but the idea is that you can ultimately peel layers off Pow as you development progress and requirements changes.

I hope this makes it clear why I think a helper like this, even if harmless, can be detrimental to Pow.

In the end all of this comes down to differing approaches. I err on the side of Elixir conventions (that I've experienced) rather than JS/Ruby. So far I feel this has worked better than when I was using devise, but time will tell whether this is the right approach.

**Comment by augnustin** [comment]
I'd be curious to read Jose about devise mistakes. As far as I'm concerned, it seems like still being the reference there, with 20k stars (out of 45k for Rails) on github. 

>  the idea is that you can ultimately peel layers off Pow as you development progress

I quite agree with that. Yes for customization, but there are layers no dev-unless-security-expert want to tackle, like encryption, security processes (reset password logic, user enumeration), session handling, cookie management etc. 

Ultimately it feels like you recommend to maintain one own fork of pow, so I guess [I'm fine with mine](https://github.com/augnustin/pow), though I'm slightly disappointed because the main reason why I migrated from coherence to pow was to use to a maintained repo, not a custom fork.

To cut the philosophical discussion short, the idea with all the issues I opened is not to criticize nor to impose my view on your repo, but simply to list all my wished requirements so that you have them in mind when working on a newer version (which you seemed to mention should come sooner or later).

If you start an issue with features to include in a new version, please do not hesitate to mention me so I can contribute.

**Comment by danschultzer** [comment]
I don't recommend forking Pow. It's problematic since you get the worst of both worlds, less secure and more maintenance. It's far better to implement these changes into your codebase as I first suggested, using the way it's shown in the guides. It would provide you the control you need, with the least amount of maintenance required.

You are trying to implement your business logic into Pow rather than leverage Pow and build your business logic on top of it. Attempts to abstract business logic in this way will open up for many pitfalls. I advice you to take a step back and review if it's possible to deal with this in a less opaque way.

> If you start an issue with features to include in a new version, please do not hesitate to mention me so I can contribute.

Sure!
