### ISSUE TITLE
Migration guide for 1.0.19?

### ISSUE THREAD

**Issue by dfalling** [danschultzer/pow#462]
I'm struggling to get my app working with the latest release.

So far I've
- manually added the `secret_key_base` to my conn in my test setup:
```elixir
    conn =
      Phoenix.ConnTest.build_conn()
      |> Map.put(:secret_key_base, Endpoint.config(:secret_key_base))
```
- changed `Plug.user_from_token` to `Plug.load_user_by_token`
- updated the handling of the above to expect tuples instead of `:ok` or `nil`
- removed `conn = conn |> Plug.assign_reset_password_user(user)`

I'm getting the following error:
```
** (FunctionClauseError) no function clause matching in Plug.Crypto.MessageVerifier.verify/2

     The following arguments were given to Plug.Crypto.MessageVerifier.verify/2:

         # 1
         nil

         # 2
         <<15, 158, 68, 11, 243, 129, 91, 185, 106, 131, 143, 210, 97, 109, 115, 232, 223, 119, 187, 113, 192, 99, 105, 16, 117, 47, 222, 126, 229, 189, 83, 2>>

     Attempted function clauses (showing 1 out of 1):

         def verify(signed, secret) when is_binary(signed) and is_binary(secret)

     code: conn = put(conn, Routes.password_reset_path(conn, :update), password_reset: valid_attrs)
     stacktrace:
       (plug_crypto) lib/plug/crypto/message_verifier.ex:30: Plug.Crypto.MessageVerifier.verify/2
       (pow) lib/extensions/reset_password/plug.ex:147: PowResetPassword.Plug.maybe_expire_token/4
```
When I try to call:
```elixir
    case Plug.update_user_password(conn, %{
           "password" => password,
           "password_confirmation" => confirm_password
         }) do
      {:ok, user, conn} ->
```

I've verified that `conn` is good going into `Plug.update_user_password`, and am not sure when it's becoming nil before `maybe_expire_token`.

**Comment by danschultzer** [comment]
Oh right, sorry about that. The message verifier can complicate the tests, but should be easy to resolve.

Can you show me the full test case? It might be easier to just rewrite so it's not too dependent on the internals.

> * removed `conn = conn |> Plug.assign_reset_password_user(user)`

You can use `Conn.assign(conn, :reset_password_user, user)` instead.

> I've verified that `conn` is good going into `Plug.update_user_password`, and am not sure when it's becoming nil before `maybe_expire_token`.

It's odd. Is it because `"id"` in `params` is nil?

**Comment by dfalling** [comment]
Thanks for the quick response!

Here's the whole relevant code from my controller:

```elixir
  def update(conn, %{
        "password_reset" => %{
          "key" => token,
          "password" => password,
          "confirm_password" => confirm_password
        }
      }) do
    case Plug.load_user_by_token(conn, token) do
      {:error, _error} ->
        conn
        |> put_status(422)
        |> json(%{error: %{status: 422, message: "Invalid reset token"}})

      {:ok, conn} ->
        update_user(conn, password, confirm_password)
    end
  end

  defp update_user(conn, password, confirm_password) do
    case Plug.update_user_password(conn, %{
           "password" => password,
           "password_confirmation" => confirm_password
         }) do
      {:ok, user, conn} ->
        config = Pow.Plug.fetch_config(conn)
        plug = Pow.Plug.get_plug(config)

        conn
        |> put_view(IdoApiWeb.PasswordResetView)
        |> plug.do_create(user, config)
        |> render("info.json", %{info: "Your password has been reset"})

      {:error, changeset, conn} ->
        conn
        |> put_status(:unprocessable_entity)
        |> put_view(IdoApiWeb.ChangesetView)
        |> render("error.json", changeset: changeset)
    end
  end
```

And the failing test:
```elixir
    test "reset password succeeds for correct key", %{conn: conn} do
      user = insert(:user)

      {:ok, %{token: token, user: user}, conn} =
        conn
        |> Pow.Plug.put_config(otp_app: :ido_api)
        |> PowResetPassword.Plug.create_reset_token(%{"email" => user.email})

      # wait to let cache write token
      :timer.sleep(1000)

      valid_attrs = %{key: token, password: "^hEsdg*F899", confirm_password: "^hEsdg*F899"}

      conn = put(conn, Routes.password_reset_path(conn, :update), password_reset: valid_attrs)

      assert json_response(conn, 200)["info"]["detail"] =~ "password has been reset"

      conn =
        post(conn, Routes.session_path(conn, :create),
          session: %{email: user.email, password: "^hEsdg*F899"}
        )

      assert response(conn, 204)
    end
```

**Comment by danschultzer** [comment]
You're missing the "id" param when calling ` Plug.update_user_password/2`:

```elixir
    case Plug.update_user_password(conn, %{
           "id" => token,
           "password" => password,
           "password_confirmation" => confirm_password
         }) do
```

That method has always required an "id" param since it uses it to validate, but I realize that it has just failed silently for you before this change. I'll see if I can make it more explicit, it should probably fail if you don't pass in the `id` or maybe there should be a token method argument.

**Comment by dfalling** [comment]
Weird, resetting passwords had worked before.  I added the `id` param but I'm getting the same error.  Are there any other changes I need?  I haven't added the `Conn.assign(conn, :reset_password_user, user)` because reset_password_user is already populated.

**Comment by danschultzer** [comment]
Yeah, the update works, the `:reset_password_user` assigns is there so the password has already been updated.

This is mostly a bug in how Pow handles the token invalidation. In theory the token is exchanged for a one time successful password update call so if the update is successful, the token is immediately invalidated. Beforehand it didn't check the token (`id` param) before it send it off to the GenServer for invalidation, so that's why it just worked even though the token was never invalidated.

I'll clean it up with #463.

I realized it's worse yet, I use `conn.params` instead of pulling from params 🤦‍♂  So you have to change it to this:

```elixir
    conn = %{conn | params: Map.put(conn.params, "id", token)}
    case Plug.update_user_password(conn, %{
           "password" => password,
           "password_confirmation" => confirm_password
         }) do
```

As soon as I got some free time I'll fix this so the `load_user_by_token` method call will carry the token information and it should just work.

**Comment by dfalling** [comment]
Perfect- that was the ticket.  That's an easy workaround until the refactor.  Thanks!

**Comment by danschultzer** [comment]
Resolved in master 🚀  Should just work now (with the code you had before) as `Plug.load_user_by_token/2` ensures to add the decoded token to `conn.private`.

**Comment by dfalling** [comment]
Great!  I'll check it out in the next release and report back if I hit any snags.  Thanks!
