### ISSUE TITLE
Unable to change email if PowEmailConfirmation is not used

### ISSUE THREAD

**Issue by jaimeiniesta** [danschultzer/pow#477]
Hello! I detected this in 1.0.7, now I have upgraded to 1.0.19 and the issue still happens:

I'm using Pow with these extensions: `extensions: [PowResetPassword, PowPersistentSession]`

Notice I'm not using `PowEmailConfirmation`. Users can sign up and log in just fine, but if they edit their accounts and change the email address, they're told everything is fine but the email is not changed.

From the logs I see that a new email confirmation is generated, but the confirmation email is not sent.

If I use the `PowEmailConfirmation` extension then users can change their email after they confirm by clicking the link sent.

**Proposed fix:**

If the `PowEmailConfirmation` extension is not used, then the users should be able to change their email without confirming it (that is, only the current password would be needed).

**Alternative fix:**

Being able to use the `PowEmailConfirmation` extension only on email change, but not on sign up.

**Comment by danschultzer** [comment]
I assume you have set your app up with `PowEmailConfirmation` originally and then removed it again? You'll need to remove it from your  User schema module as well, otherwise the `PowEmailConfirmation` changeset kicks in.

The `email_confirmation_token`, `email_confirmed_at` and `unconfirmed_email` fields only gets added if you had `PowEmailConfirmation` enabled, and the changeset will only kick in if `PowEmailConfirmation` is still enabled.

**Comment by jaimeiniesta** [comment]
Ah! That was it, of course! I had removed the extension from the `config` but forgot to remove it from the User schema as well. 🤦‍♂ 

Thanks! 😃
