### ISSUE TITLE
Should the `email_confirmation_required` message be really an `:error` flash?

### ISSUE THREAD

**Issue by thiagomajesk** [danschultzer/pow#498]
> You'll need to confirm your e-mail before you can sign in. An e-mail confirmation link has been sent to you.

Just noticed this week after configuring Pow in a new web app (and styling some alert components), that [this message](https://github.com/danschultzer/pow/blob/master/lib/extensions/email_confirmation/phoenix/messages.ex#L22) is [being issued](https://github.com/danschultzer/pow/blob/master/lib/extensions/email_confirmation/phoenix/controllers/controller_callbacks.ex#L99) as an `:error` flash. 

I thought about that for some time and to me at least, this message doesn't sound like an `:error`. 
If this makes sense, shouldn't this be changed to an `:info` or a `:warn` flash!?

I usually reserve the "error" messages for exceptional cases, like validations and server errors and everything else is a warning or just a piece of information to the end-user. And right now, I'm having to deal with this specific message like it was an error, which I find really odd:

![ss](https://user-images.githubusercontent.com/13930952/79908178-26d3e780-83f1-11ea-8138-3b45aefd2091.png)

Currently, I'm having a problem with this behavior and would like to know if this is up for change. If not, I'd like to know if it can be changed at all, not the message, not the logic behind it, just the way the flash is being issued. 

Also, thanks a lot for all the hard work in maintaining this project 😊. Cheers!

**Comment by danschultzer** [comment]
Thanks!

There's no `:warn` flash in the default Phoenix install, so only other option is `:info`. I chose `:error` since it's unexpected that you can't sign in, just as if the credentials were invalid. So the current logic follows the convention in Phoenix pretty tightly, as there is no `:warn` type flash.

The flash type in Pow can only be changed if you set up custom controllers and override the logic, and I'm not sure if it makes sense to make it configurable as it follows the default Phoenix behavior.

I would suggest using a different flash type for stronger errors. It could look something like this:

```elixir
conn
|> put_flash(:error, "Something unexpected happened")
|> put_flash(:alert, "Oh god, something really went wrong here")
```

```elixir
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

<%= if alert = get_flash(@conn, :alert) do %>
<p class="alert alert-danger" role="alert"><%= alert %></p>
<% end %>
```

Also, I've only seen the `Ops! Something is wrong` type message inside the forms that Phoenix generate 😄

**Comment by thiagomajesk** [comment]
Hi @danschultzer! Thanks for the reply.

I'm aware that there's not `:warn` flashes in Phoenix, my suggestion was precisely to avoid clashing with the existing `:error` and `:info` in new projects 😄. 

Although, I wouldn't call it a "convention", the docs say that those atoms are only handled by default because it's in the templates, which for most cases, will be eventually changed to accommodate the project's needs.

In the end, after letting the information sink a bit, I think I can get behind the choice that was made about using just this option. I guess it just doesn't make sense to impose just another convention of doing something that does not ship by default, although for that particular case I'd much prefer the `:info` message than `:error` haha. 
I don't know if there is something that yells stronger than "error" though, at least in my head "error" and "unexpected" are in separate boxes. I'm afraid Bootstrap kinda standardized this for me, so I'd expect: `info`, `success`, `warning`, `danger` (`error`).

Thanks for your time. Cheers! 😊

**Comment by danschultzer** [comment]
Yeah, I agree, the naming is not great. It makes more sense if the `:error` flash message was called `:warn` by default, because even with errors in changeset you can still argue that it's expected behavior. `:danger` could work as name for unexpected error flash 😄

**Comment by patrickbiermann** [comment]
Hi @danschultzer, first off: Thank you for a great library!

In our development we have encountered the same issue as @thiagomajesk. The `:error` flash message seems inappropriately used in this instance, since the user receives the feedback that something went wrong. In our user tests this was a common theme. I understand that the convention of Phoenix flash messages does not have a `:warn` message, but we believe that in this instance the `:info` flash message would be an improved user-centric approach.

Alternatively, we would suggest, that a user is redirected to a new page where the next steps (email confirmation and so on) are described instead of showing a flash message at all.

We would love to hear your thoughts.

Thank you for your time. Cheers!

**Comment by thiagomajesk** [comment]
To this day this is something that still causes confusion in the company I work and we haven't changed it yet... 
Once in a while, someone asks why we have this big red information message screaming at them there 😅 haha. 

I have to agree with @patrickbiermann that using `:info` for this specific flash message would improve the end-user experience. 
Analyzing the standard user interaction over this last year, I think that even though the underlying logic is considered to "fail", in this case, I'd argue that there's no correlation between the underlying error/ system representation and what the user should see as a result.

**Comment by danschultzer** [comment]
Yeah, I agree! I've updated it in #612, will merge and release a new version today 😄

**Comment by patrickbiermann** [comment]
@danschultzer Thank you very much, that's great!
