### ISSUE TITLE
Small note on mailer templates documentation.

### ISSUE THREAD

**Issue by kurisusan** [danschultzer/pow#547]
Hi,
It's stated in this [part of Pow README (Modify mailer templates)](https://github.com/danschultzer/pow#modify-mailer-templates)

> This will generate view files in WEB_PATH/views/mailer/, and html and text templates in WEB_PATH/templates/mailer directory.

But generated templates and views are instead located in "WEB_PATH/views/POW_EXTENSION/" and "WEB_PATH/templates/POW_EXTENSION".

It's not a big deal, but I was expecting all mailer templates grouped in the same folder "mailer" but there are generated into their corresponding extension folder. (Of course, this is very practical as well.)

**Comment by danschultzer** [comment]
Thanks, I've updated the readme!

I do wonder if it makes more sense to put all mailer templates into `/mailer/POW_EXTENSION` instead of `/POW_EXTENSION/mailer`?

My thought process when I was setting this up is that we would want all the templates (controller and mailer) for each extension to be in the same directory so if you decide to remove an extension you only have to delete that one directory in templates.
