### ISSUE TITLE
Creating dynamic tenants flow

### ISSUE THREAD

**Issue by denvaar** [danschultzer/pow#608]
I've been reading the [Multitenancy](https://hexdocs.pm/pow/multitenancy.html#content) guide. It goes over how ensure that Pow is aware of the current tenant and how to utilize the Triplex package. One thing I have been trying to figure out, however, is what the flow should look like for when a new tenant (eg. database schema) needs to be created as part of user registration.

For example, an application might have a sign up form, allowing a user to specify an account (aka the tenant). When the form is submitted, I imagine the following things need to happen:

1. `Triplex.create(account)` needs to run so as to create a database schema for the new tenant.
2. `repo_opts` needs to be updated with the correct `prefix` (as seen in the TriplexSessionPlug example).
3. `Pow.Plug.create_user` needs to run after Pow has been configured to have the right prefix.

Ideally, the schema creation and the creation of the actual user itself should be within a transaction.

I'm not sure what the best way to handle this is, and I think it would be a helpful addition to the docs. I'd be happy to update the docs once I know the preferred way to do it (custom controller maybe?)

**Comment by danschultzer** [comment]
> For example, an application might have a sign up form, allowing a user to specify an account (aka the tenant)

The steps seems good. I don't have much experience with triplex but I imagine you want to run the tenant and user creation in a transaction? If that's the case, then you should just call `Pow.Ecto.Context.create(params, config)` in the transaction if the transaction succeeds then `Pow.Plug.create(conn, user, config)`. No need to call `Pow.Plug.create_user/2`.

For `config` in the above you just need something like `[otp_app: :my_app, repo_opts: [prefix: prefix]]`.

> I'd be happy to update the docs once I know the preferred way to do it (custom controller maybe?)

Please do!

Also, an alternative I want to explore is using the process dictionary. I like a lot the idea of setting the repo opts in the process with `Process.put(:repo_opts, [prefix: prefix])` instead of passing the argument all the way from the plug conn. Just a though I've had no time to explore 😄

**Comment by denvaar** [comment]
I was able to get this taken care of using a custom registration controller. I realized something like this is mostly application-specific, but I tried to update the guide with at least a couple things that would be general enough and helpful. Thank you!
