### ISSUE TITLE
Function to return total users count.

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#68]
I wonder which is the better way to get total registered users count.

How about adding a function to return the count of total users?

1) Return the max `id` in `users` table.
- Fast but not precise.
- Not applicable except auto-increment id; ex. UUID.

2) Return the count of primary key in `users` table.
- Rather fast and precise.

**Comment by danschultzer** [comment]
Definitely 2. But as for implementation, I think rather than being part of Pow, it's better to let the developer add a context module with their custom methods:

```elixir
defmodule MyApp.Users do
  alias MyApp.{Repo, Users.User}

  @spec count() :: integer()
  def count() do
    Repo.aggregate(User, :count, :id)
  end
end
```

This will work in parallel with the Pow context methods, and is cleaner since `count/0` isn't needed for anything in Pow. It'll also give more power to the developer as for how the count is retrieved.

**Comment by jung-hunsoo** [comment]
Agreed.

There's already a context module for other functions.

Thanks.
