### ISSUE TITLE
Use Postgres for session storage?

### ISSUE THREAD

**Issue by kidbombay** [danschultzer/pow#76]
What are the trade offs of using Postgres for session storage?

**Comment by danschultzer** [comment]
You’ll have to make the same module as in #75, but also set it up as a GenServer to ensure that the session data expires with a TTL. Session data should be ephemeral, and is key-value based so a relational db like Postgres isn’t the right tool for the job. Still it would work, as long as you serialize the data when storing it.

Redis is the easiest alternative to Mnesia, since you won’t have to deal with TTL. Any other key-value store you have access to would probably work well too. Alternatively you could also keep a distributed in-memory ETS if you’ll have multiple servers running. There is a lot of careful considerations to be made with that option though.
