### ISSUE TITLE
Why not add fields to user schema explicit way instead of using pow_user_fields() function?

### ISSUE THREAD

**Issue by DiodonHystrix** [danschultzer/pow#94]
Ok, why? I like that Ecto is enforcing defining schema with all fields. I come from the Rails world where everything is hidden. And when I look at that newly generated schema by `pow` I'm missing the fields it generated for me. Because of it, the explicitness has disappeared and I feel like I'm back in Rails.

I know that counter argument could be that routes are done similar way, but there I can use `mix phx.routes` and then I can see everything.

Wdyt?

**Comment by danschultzer** [comment]
It's a good point. I far prefer everything to be explicit, and of course nothing hinders you from just writing out all the fields yourself.

The biggest reason is to make it simpler to enable extensions:

```elixir
use Pow.Extension.Ecto.Schema,
  extensions: [PowExtensionOne, PowExtensionTwo]

schema "users" do
  pow_user_fields() # This will also have fields from PowExtensionOne and PowExtensionTwo

  timestamps()
end
```

Furthermore, the `pow_user_fields/0` macro has a similar purpose to the `timestamps/1` macro, and the implicit `:id` field, as there will be a third party library that populates these fields. By letting developers manage the fields right away (and in particular virtual fields that definitely should stay virtual) it could make it more difficult to ensure everything works as expected.

Instead I prefer that developers expand on the fields themselves when necessary. It's possible to [define some fields that Pow will use, and let the rest be handled by the macro](https://github.com/danschultzer/pow/pull/21):

```elixir
schema "users" do
  field :password_hash, :string, source: :encrypted_password

  pow_user_fields()

  timestamps()
end
```

This is how I like Pow to be most of the time. Rather than writing out everything from the start explicitly, Pow makes it possible to extract certain parts that will be explicit, and easy to test. Templates are another example of this thinking.

In case you want to see how it looks under the hood:

https://github.com/danschultzer/pow/blob/356a610c34f44e7f37bf71e455b0efe4e1e2a11d/lib/pow/ecto/schema.ex#L146-L162

https://github.com/danschultzer/pow/blob/356a610c34f44e7f37bf71e455b0efe4e1e2a11d/lib/pow/ecto/schema/fields.ex#L7-L12

**Comment by danschultzer** [comment]
Another way to think about it is that the changeset is handled in the Pow library, so the fields should be handled by it too. But it's hard to find the right balance, so please let me know if you have any suggestions how this could be improved.

I definitely want to make Pow as explicit as possible, and let Pow documentation help developers think in that way too 😄

**Comment by DiodonHystrix** [comment]
Hmm, thanks for the answer. I see your point, if someone is gonna use `pow` they may not need that information at all, because they trust `pow` to take care of it. After reading it I guess I understand my problem a bit more. That `timestamps/1` analogy helped. I think what I struggled with was an easy way to find out (preferably from docs) what fields that macro generates.

Take a look at `timestamps/1` [docs](https://hexdocs.pm/ecto/Ecto.Schema.html#timestamps/1). It lists what kind of fields there will be generated.

Maybe just adding proper information via docs, would be enough.

Btw. Really liked the code so far! There are a lot of things taken care of and it makes it pretty easy to adjust it to my needs, at least so far :smile:

**Comment by danschultzer** [comment]
That's great to hear! Don't hesitate to write about any other things in Pow that's confusing or could be improved. It helps a lot :smile:

I've opened #96 to improve the docs on `pow_user_fields/0` and Pow Ecto fields.

**Comment by DiodonHystrix** [comment]
Looks very cool! Thanks for such a quick response. If I get any more feedback or questions, I will surely open an issue.
