### ISSUE TITLE
Should a new extension be added as a new package or here?

### ISSUE THREAD

**Issue by DiodonHystrix** [danschultzer/pow#99]
Hey, I'm working on an invitation extension (to invite new users). I'm not sure if I should make a new package like pow_assent or maybe I should submit a PR here?

What would be the best option in your opinion?

**Comment by danschultzer** [comment]
I would love a PR! This is something I prefer to be part of Pow, unless it has significant amount of code/logic/configuration.

I was working on an invitation extension myself, but it was tricky since there’re many different ways of handling invitation. I’ll post some examples and thoughts on this later when I got time.

**Comment by DiodonHystrix** [comment]
Thanks for the information, I should have something by the end of next week.

Is there any guide on how to set up repo locally?

I have that kind of message after running `mix test`:

> You have configured application PowEmailConfirmation.Test in your configuration file,
> but the application is not available.
> 
> This usually means one of:
> 
>   1. You have not added the application as a dependency in a mix.exs file.
> 
>   2. You are configuring an application that does not really exist.
> 
> Please ensure PowEmailConfirmation.Test exists or remove the configuration.
> 
> You have configured application PowResetPassword.Test in your configuration file,
> but the application is not available.
> 
> This usually means one of:
> 
>   1. You have not added the application as a dependency in a mix.exs file.
> 
>   2. You are configuring an application that does not really exist.
> 
> Please ensure PowResetPassword.Test exists or remove the configuration.
> 
> You have configured application PowPersistentSession.Test in your configuration file,
> but the application is not available.
> 
> This usually means one of:
> 
>   1. You have not added the application as a dependency in a mix.exs file.
> 
>   2. You are configuring an application that does not really exist.
> 
> Please ensure PowPersistentSession.Test exists or remove the configuration.
>

**Comment by danschultzer** [comment]
Sorry for the delay, I have had no time these last few days.

The warnings were because of the config [for extension tests](https://github.com/elixir-lang/elixir/blob/3a3d68385ef02148136ff4b9490c70d3e6d3dbc3/lib/mix/lib/mix/tasks/app.start.ex#L170-L189). I've fixed this by moving config in #100.

You don't have to set up the repo locally, since it's already done in the test helper. You just need to have Postgres installed.

I'm writing a Contributing section to the readme, and after that I'll post my thoughts on the invitation extension here.

**Comment by danschultzer** [comment]
I've added this section to the readme: https://github.com/danschultzer/pow/blob/871738765bf6ab9623eeb40afb0cdacd977bcdcf/README.md#contributing

So let's get back to the invitation extension. What I prefer to do with all extensions is to try figure out the essence of what the extension should do, and attempt to leave enough room for developers to expand upon it if possible.

I think the essence of invitation extension for most would be to restrict sign up. Pow can be set up without e-mail requirement (e.g. like reddit) so the basis of the extension is to generate a token that can be shared/used for registration.

The tokens can be stored in the database or in the cache backend. Personally, I prefer that invitation tokens are transient with a TTL (e.g. 14 days), so I would choose the cache backend as default.

This may be a good setup:

* Unique one-time use invitation tokens stored in cache store backend
* Require `:invitation_token` param on user registration
* `:inviter_user_id` reference in user schema
* A Phoenix controller/view/template for creating an invitation

One issue is that the one-time use invitation tokens can be weird UX wise when there is no e-mail to share it with. However, this will be relevant for only extremely few cases so we don't need to think about it too much.

To make it plug n' play, there should be invitation e-mail included in this extension that is used if an `:email` field on the user schema is detected. This should be done in the controller.

This is what I imagine developers may want to expand on:

* Controller/view for managing invitations
* Store tokens in the database
* Limit number of invitations per user
* Make invitation optional
* Restrict to e-mail that was invited

PowAssent should also be updated to detect if invitation extension is enabled to prevent signups without valid token.

This is the overview of it. There are a lot of things that will become clear when the code is written, so there may be things that can be improved with how extensions works. Please let me know if you encounter any issues or something missing 😄 

I try to make configuration of Pow as explicit as possible, so instead of using a config option, developers extract and configure what they need. So when I was writing some of the code for this I was thinking about optional vs required invitation token. It may be easier to have it optional as default, and then let developers add e.g. a plug or custom route/scope to require the token. However, I think most would want to require token, and it's better to make it as easy as possible to plug in these extensions.

This was a pretty long reply, but I want to give a good idea of what went through my head when I was looking at this extension.

**Comment by DiodonHystrix** [comment]
I managed to run `mix test` successfully :) I had errors from the `Mix.Task.run("ecto....` inside `test_helper` and they weren't printed, so it took me a while to find the problem. I had to run them manually like `MIX_ENV=test mix ecto.drop` to see the errors.

That description is very detailed, wow. Nice! I haven't had much time to get into it yet. I think I will start from that invitation token + controller and submit PR to see if that's what you had in mind :) Thanks for your help, really appreciate it.

**Comment by danschultzer** [comment]
Oh, good call, the shell messages were suppressed before they were supposed to be. I've merged in a fix!

**Comment by danschultzer** [comment]
So I've ben thinking about this extension, and I think there're several things that needs to be changed in Pow to make this extension possible.

I've opened a draft PR #113 with the initial work to store token and require `:invitation_token` param on user registration. There are also some commits with bug fixes and refactoring that I'll pull into another PR.

The biggest hurdle I've now is to figure out how to safely pass `inviter_user` from the controller to ecto changeset. Also, only the Ecto migration generation handles references right now, and I'll need to refactor this so the schema module can use reference fields (support was added for PowAssent, but I hard-coded the `belongs_to` there).

Adding controllers/view/email will be easy though.

**Comment by danschultzer** [comment]
Ok, I decided to rethink it all and simplify it. The new process is documented in #113, with a working example.

**Comment by DiodonHystrix** [comment]
Oh, I haven't had time to do it myself. Tried to work on it another day, but I realized that there were too many changes to be made and I hadn't studied the code enough.

It seems that you managed to ship it all by yourself, though. Nice :1st_place_medal: I will have a look at the code tomorrow, because I'm really curious how it's done.
